#!/usr/bin/python
#
#   output_numeric_common.py --  the generated-python pieces both numerical
#                                methods need
#
#   The hybrid method and the one-variable method each write python modules
#   that run on their own.  The parts neither method owns live here:  printing
#   a sympy expression as python, what such a module may import, the forward
#   kinematics of an arm as a callable, and the measure of how far one pose is
#   from another.
#
#   Copyright 2026 University of Washington
#
#   Developed by Blake Hannaford
#   BioRobotics Lab, University of Washington

import os

import sympy as sp

import ikbtbasics.numeric_ik as nik
from ikbtfunctions.output_python import py_identifier


DIR_NAME = os.path.join('CodeGen', 'Python')

#  Everything a generated module may call.  `Abs` is printed as the builtin
#  abs();  the rest come from math, the way the IK modules already import
#  them.
#
#  'Abs' with a capital A, because the check below compares the CLASS NAME of
#  each sympy function in the expression, and sympy's absolute value is the
#  class Abs.  Nothing is named lowercase 'abs', so that spelling would match
#  no expression and quietly refuse every one containing an absolute value.
ALLOWED_FUNCS = {'sin', 'cos', 'tan', 'asin', 'acos', 'atan', 'atan2',
                 'sqrt', 'Abs', 'exp', 'log'}

MODULE_HEADER = '''#!/usr/bin/python
#  **WHAT**
#
#  Generated by IKBT.  Do not edit:  regenerate with
#      python3 ikSolver.py **ROBOT**

import numpy as np
from math import sqrt
from math import atan2
from math import cos
from math import sin
from math import acos
from math import asin

pi = np.pi
'''


def expr_py(e):
    '''Python source for one sympy expression, or a raised ValueError.

       sp.pycode() with fully_qualified_modules=False writes exactly what a
       generated module already understands -- plain sin/cos/sqrt/atan2 and a
       plain pi -- so nothing has to be patched up afterwards.'''

    src = sp.pycode(e, fully_qualified_modules=False)
    if 'ImmutableDenseMatrix' in src or 'Not supported' in src:
        raise ValueError('cannot express in python: %s' % str(e)[:120])
    for f in e.atoms(sp.Function):
        nm = type(f).__name__
        if nm not in ALLOWED_FUNCS:
            raise ValueError('generated python would need %s(), which the '
                             'module does not import' % nm)
    return src


def _matrix_py(Mx, indent):
    '''A sympy Matrix as a numpy array literal, one row per line.'''

    rows = []
    for i in range(Mx.rows):
        cells = ', '.join(expr_py(Mx[i, j]) for j in range(Mx.cols))
        rows.append('%s[%s]' % (indent + '     ', cells))
    return ('np.array([\n' + ',\n'.join(rows) + '\n' + indent + '    ], '
            'dtype=float)')


###############################################################################
#
#    FK (and Jacobian) for one arm
#

def write_fk_module(M, name, jacobian=True, dirname=DIR_NAME, what=None):
    '''Write FK_numeric<name>.py:  fk_<name>(q), and optionally jacobian_<name>(q).

       FK_numeric, never FK_equations.  output_python.output_FK_python_code()
       already owns the name FK_equations<name>.py -- that is what fkOnly.py
       writes, and it is a different thing:  the symbolic T_06 written out to
       be read, with dummy joint values.  This one is a pair of functions you
       call, with the link lengths already substituted in.  One name for both
       would mean whichever ran last quietly replaced the other.

       M         a mechanism (Robot.Mech) -- T_06 and J66 come from it
       name      the robot name this arm is;  also the file name
       jacobian  emit the Jacobian too (Phase II needs it, plain FK does not)
       what      one line for the file header, describing which arm this is

       Returns the path written.

       THE LINK LENGTHS ARE SUBSTITUTED IN, not left as module variables a
       caller could change.  IK_equations*.py does the opposite, on purpose:
       these two functions ARE the definition of "the true arm" that the
       hybrid method's correction step measures against, so they must not be
       quietly pointed at a different robot.

       The numerical values come from numeric_ik.pvals_numeric().'''

    ident = py_identifier(name)
    ndof = M.ndof
    syms = nik.joint_symbols(M, ndof)
    pv = nik.pvals_numeric(M)

    T = sp.Matrix(M.T_06).subs(pv)
    #  Only the first ndof columns of J66.  It is stored 6x6 for every robot
    #  and the surplus columns of a short arm are NOT zero -- a padded DH row
    #  still gets a column computed for it -- so handing them to the solver
    #  would let it move joints the arm does not have.
    J = sp.Matrix(M.J66).subs(pv)[:, :ndof] if jacobian else None

    for label, Mx in (('T_06', T), ('J66', J)):
        if Mx is None:
            continue
        extra = sorted(Mx.free_symbols - set(syms), key=str)
        if extra:
            raise ValueError('%s of %s still contains %s -- pvals did not '
                             'resolve every parameter'
                             % (label, name, [str(s) for s in extra]))

    #  CodeGen/Python/ is a GENERATED directory and is not in a fresh clone
    #  (.gitignore has CodeGen/*).  Make it, the way the fk_eqns/ cache and
    #  graphs/ and logs/ already make themselves.
    if not os.path.isdir(dirname):
        os.makedirs(dirname)

    path = os.path.join(dirname, 'FK_numeric%s.py' % name)
    with open(path, 'w') as f:
        hdr = MODULE_HEADER.replace('**ROBOT**', name)
        hdr = hdr.replace('**WHAT**', what or
                          'Forward kinematics for %s' % name)
        print(hdr, file=f)

        print('#  Joint order is the DH CHAIN order, which is what a q vector', file=f)
        print('#  must be in.  It is NOT the order the solver happened to', file=f)
        print('#  solve them in, and it excludes sum-of-angle intermediates.', file=f)
        print('JOINT_NAMES = %r' % [str(s) for s in syms], file=f)
        print('NDOF = %d' % ndof, file=f)
        print('', file=f)

        unpack = ', '.join(str(s) for s in syms)
        print('', file=f)
        print('def fk_%s(q):' % ident, file=f)
        print("    '''q -> 4x4 homogeneous transform of frame 6 in the base frame.'''", file=f)
        print('    %s = [float(v) for v in q]' % unpack, file=f)
        print('    return ' + _matrix_py(T, '    '), file=f)
        print('', file=f)

        if jacobian:
            print('', file=f)
            print('def jacobian_%s(q):' % ident, file=f)
            print("    '''q -> 6 x %d Jacobian, EXPRESSED IN FRAME 6." % ndof, file=f)
            print('', file=f)
            print('       Frame 6, not the base frame:  that is what IKBT', file=f)
            print('       computes and stores as J66.  Rotate it with', file=f)
            print('       jacobian_base() before comparing against a pose', file=f)
            print('       error, which lives in the base frame.', file=f)
            print("    '''", file=f)
            print('    %s = [float(v) for v in q]' % unpack, file=f)
            print('    return ' + _matrix_py(J, '    '), file=f)
            print('', file=f)

    return path




###############################################################################
#
#    How far one pose is from another
#

#  Copied verbatim into every generated numerical module, so that both
#  methods measure "closer" the same way.  The residual [dp ; w_rot*theta*axis]
#  and the single number ||dp|| + w_rot*theta describe the rotation the same
#  way and use the same weight, so a hybrid refinement and a one-variable
#  search cannot disagree about which of two joint vectors is nearer the
#  goal.

POSE_ERROR_CORE = '''

#############################################################
#
#   Pose error:  the residual, and the scalar metric built from it
#
#############################################################


def rotation_angle_axis(Rerr):
    """(theta, axis) of a rotation matrix, theta in [0, pi].

       THETA COMES FROM atan2 OF THE SKEW NORM, NOT arccos((tr-1)/2).  arccos
       has an infinite slope at R = I, so rounding of order 1e-16 in the trace
       comes back out as an angle of order 1e-8 radians, which w_rot turns
       into 1e-6 in the metric.  That is an error floor no search can see
       past, and it comes in steps, so the error curve near a solution is a
       staircase rather than a clean V.  atan2 of the skew norm grows linearly
       with the perturbation and gives exactly 0.0 at R = I.  dh_analysis.py
       computes its angles the same way, for the same reason."""
    Rerr = np.asarray(Rerr, dtype=float)
    skew = np.array([Rerr[2, 1] - Rerr[1, 2],
                     Rerr[0, 2] - Rerr[2, 0],
                     Rerr[1, 0] - Rerr[0, 1]])
    s = float(np.linalg.norm(skew))
    theta = float(np.arctan2(0.5 * s, (np.trace(Rerr) - 1.0) / 2.0))
    if theta < 1e-12:
        return 0.0, np.zeros(3)
    if theta < np.pi - 1e-6:
        return theta, skew / s          # s = 2*sin(theta), never 0 here
    #  theta ~ pi: the skew part vanishes, so take the axis from R + I = 2aa'
    Msym = Rerr + np.eye(3)
    j = int(np.argmax(np.linalg.norm(Msym, axis=0)))
    axis = Msym[:, j]
    n = np.linalg.norm(axis)
    if n < 1e-12:
        return theta, np.zeros(3)
    return theta, axis / n


def pose_error(T, T_d, w_rot=W_ROT):
    """(6-vector residual, scalar metric) between pose T and target T_d."""
    T = np.asarray(T, dtype=float)
    T_d = np.asarray(T_d, dtype=float)
    dp = T_d[:3, 3] - T[:3, 3]
    theta, axis = rotation_angle_axis(T_d[:3, :3] @ T[:3, :3].T)
    return (np.concatenate([dp, w_rot * theta * axis]),
            float(np.linalg.norm(dp) + w_rot * theta))
'''
