#!/usr/bin/python
#
#   output_numeric_common.py --  generated-python pieces more than one method needs
#
#   The hybrid method and the one-variable method both emit standalone numeric
#   modules, and they agree about the parts that are not specific to either:
#   how a sympy expression becomes python, what a generated module may import,
#   the FK callable for an arm, and how far one pose is from another.
#
#   It lives apart from output_hybrid_python.py because the one-variable branch
#   is not hybrid.  Importing an arm's FK writer from a module named for the
#   hybrid method would say the wrong thing about which method owns it -- and
#   this repo's naming rules exist precisely so that opening a file tells you
#   what it is.  output_hybrid_python re-exports these names, so every existing
#   caller (ohp.write_fk_module, ohp.expr_py) still works.
#
#   Copyright 2026 University of Washington
#
#   Developed by Blake Hannaford
#   BioRobotics Lab, University of Washington

import os

import sympy as sp

import ikbtbasics.numeric_ik as nik
from ikbtfunctions.output_python import py_identifier


DIR_NAME = os.path.join('CodeGen', 'Python')

#  Everything the generated modules may call.  `abs` is a builtin;  the rest
#  come from math, exactly as the existing IK modules import them.
ALLOWED_FUNCS = {'sin', 'cos', 'tan', 'asin', 'acos', 'atan', 'atan2',
                 'sqrt', 'abs', 'exp', 'log'}

MODULE_HEADER = '''#!/usr/bin/python
#  **WHAT**
#
#  Generated by IKBT.  Do not edit:  regenerate with
#      python3 ikSolver.py **ROBOT**

import numpy as np
from math import sqrt
from math import atan2
from math import cos
from math import sin
from math import acos
from math import asin

pi = np.pi
'''


def expr_py(e):
    '''Python source for one sympy expression, or a raised ValueError.

       sp.pycode() with fully_qualified_modules=False emits exactly the dialect
       the generated modules already support -- bare sin/cos/sqrt/atan2 and a
       bare pi -- so nothing has to be post-processed into shape.

       THE GUARD IS THE POINT.  A function this module cannot promise is
       importable in the generated file (say a Piecewise, or a sympy-only
       special function) would emit source that imports cleanly and then raises
       NameError at the first call, from inside generated code, with no
       indication of which expression was at fault.  Refusing here names it.'''

    src = sp.pycode(e, fully_qualified_modules=False)
    if 'ImmutableDenseMatrix' in src or 'Not supported' in src:
        raise ValueError('cannot express in python: %s' % str(e)[:120])
    for f in e.atoms(sp.Function):
        nm = type(f).__name__
        if nm not in ALLOWED_FUNCS:
            raise ValueError('generated python would need %s(), which the '
                             'module does not import' % nm)
    return src


def _matrix_py(Mx, indent):
    '''A sympy Matrix as a numpy array literal, one row per line.'''

    rows = []
    for i in range(Mx.rows):
        cells = ', '.join(expr_py(Mx[i, j]) for j in range(Mx.cols))
        rows.append('%s[%s]' % (indent + '     ', cells))
    return ('np.array([\n' + ',\n'.join(rows) + '\n' + indent + '    ], '
            'dtype=float)')


###############################################################################
#
#    FK (and Jacobian) for one arm
#

def write_fk_module(M, name, jacobian=True, dirname=DIR_NAME, what=None):
    '''Write FK_numeric<name>.py:  fk_<name>(q), and optionally jacobian_<name>(q).

       FK_numeric, NOT FK_equations.  output_python.output_FK_python_code()
       already owns FK_equations<name>.py -- that is what fkOnly.py writes,
       and it is a different artifact: a module-level dump of the symbolic
       T_06 for reading, with dummy joint values.  This one is a pair of
       numeric callables with the parameters baked in.  Sharing a filename
       would mean whichever ran last silently replaced the other.

       M         a mechanism (Robot.Mech) -- T_06 and J66 come from it
       name      the robot name this arm is;  also the file name
       jacobian  emit the Jacobian too (Phase II needs it, plain FK does not)
       what      one line for the file header, describing which arm this is

       Returns the path written.

       THE PARAMETERS ARE BAKED IN, not left as module globals to be overridden.
       That is the opposite of what IK_equations*.py does, and deliberately:
       these two functions are the definition of "the true arm" that Phase II
       refines against, and a caller who edited a link length here would move
       the target without moving the closed form that seeds it.  Editing the
       robot means regenerating.

       pvals is resolved through numeric_ik.pvals_numeric(), NOT read raw:
       for a non-right-angle alpha kin_cl evaluates sin/cos to a number, but
       falls back to the STRING 'np.cos(al_1)' when the twist's own symbols have
       no numeric value -- and a raw read then leaves al_1 as a free symbol that
       silently becomes a joint argument.'''

    ident = py_identifier(name)
    ndof = nik.dof_of(M)
    syms = nik.joint_symbols(M, ndof)
    pv = nik.pvals_numeric(M)

    T = sp.Matrix(M.T_06).subs(pv)
    #  Only the first ndof columns of J66.  It is stored 6x6 for every robot
    #  and the surplus columns of a short arm are NOT zero -- a padded DH row
    #  still gets a column computed for it -- so handing them to the solver
    #  would let it move joints the arm does not have.
    J = sp.Matrix(M.J66).subs(pv)[:, :ndof] if jacobian else None

    for label, Mx in (('T_06', T), ('J66', J)):
        if Mx is None:
            continue
        extra = sorted(Mx.free_symbols - set(syms), key=str)
        if extra:
            raise ValueError('%s of %s still contains %s -- pvals did not '
                             'resolve every parameter'
                             % (label, name, [str(s) for s in extra]))

    path = os.path.join(dirname, 'FK_numeric%s.py' % name)
    with open(path, 'w') as f:
        hdr = MODULE_HEADER.replace('**ROBOT**', name)
        hdr = hdr.replace('**WHAT**', what or
                          'Forward kinematics for %s' % name)
        print(hdr, file=f)

        print('#  Joint order is the DH CHAIN order, which is what a q vector', file=f)
        print('#  must be in.  It is NOT the order the solver happened to', file=f)
        print('#  solve them in, and it excludes sum-of-angle intermediates.', file=f)
        print('JOINT_NAMES = %r' % [str(s) for s in syms], file=f)
        print('NDOF = %d' % ndof, file=f)
        print('', file=f)

        unpack = ', '.join(str(s) for s in syms)
        print('', file=f)
        print('def fk_%s(q):' % ident, file=f)
        print("    '''q -> 4x4 homogeneous transform of frame 6 in the base frame.'''", file=f)
        print('    %s = [float(v) for v in q]' % unpack, file=f)
        print('    return ' + _matrix_py(T, '    '), file=f)
        print('', file=f)

        if jacobian:
            print('', file=f)
            print('def jacobian_%s(q):' % ident, file=f)
            print("    '''q -> 6 x %d Jacobian, EXPRESSED IN FRAME 6." % ndof, file=f)
            print('', file=f)
            print('       Frame 6, not the base frame:  that is what IKBT', file=f)
            print('       computes and stores as J66.  Rotate it with', file=f)
            print('       jacobian_base() before comparing against a pose', file=f)
            print('       error, which lives in the base frame.', file=f)
            print("    '''", file=f)
            print('    %s = [float(v) for v in q]' % unpack, file=f)
            print('    return ' + _matrix_py(J, '    '), file=f)
            print('', file=f)

    return path




###############################################################################
#
#    How far one pose is from another
#

#  Emitted verbatim into every generated numeric module.  ONE definition of
#  "closer" across the methods:  the residual [dp ; w_rot*theta*axis] and the
#  scalar metric ||dp|| + w_rot*theta share one rotation parameterisation and
#  one weight, so a hybrid refinement and a one-variable search cannot disagree
#  about which of two joint vectors is nearer the goal.
#
#  A copy, because a generated module stands on numpy alone and cannot import
#  IKBT.  It is pinned by TestSolver024, which runs the generated code and
#  ikbtbasics/numeric_ik.py on the same robot and requires the same answer.
#
#  W_ROT is a module constant of the GENERATED file, baked in per robot:
#  nothing records a model's units and they are not consistent across the robot
#  set, so the weight is one characteristic arm length per radian.
POSE_ERROR_CORE = '''

#############################################################
#
#   Pose error:  the residual, and the scalar metric built from it
#
#############################################################


def rotation_angle_axis(Rerr):
    """(theta, axis) of a rotation matrix, theta in [0, pi].

       THETA COMES FROM atan2 OF THE SKEW NORM, NOT arccos((tr-1)/2).  arccos
       has an infinite derivative at R = I, so the O(1e-16) rounding in the
       trace comes back out as O(1e-8) radians, and w_rot scales that to
       O(1e-6) in the metric -- a floor no search can see past, and one that
       is quantised, so the curve near a root is a staircase rather than a V.
       atan2 is linear in the perturbation and gives exactly 0.0 at R = I.
       Same reasoning, and the same fix, as dh_analysis.py."""
    Rerr = np.asarray(Rerr, dtype=float)
    skew = np.array([Rerr[2, 1] - Rerr[1, 2],
                     Rerr[0, 2] - Rerr[2, 0],
                     Rerr[1, 0] - Rerr[0, 1]])
    s = float(np.linalg.norm(skew))
    theta = float(np.arctan2(0.5 * s, (np.trace(Rerr) - 1.0) / 2.0))
    if theta < 1e-12:
        return 0.0, np.zeros(3)
    if theta < np.pi - 1e-6:
        return theta, skew / s          # s = 2*sin(theta), never 0 here
    #  theta ~ pi: the skew part vanishes, so take the axis from R + I = 2aa'
    Msym = Rerr + np.eye(3)
    j = int(np.argmax(np.linalg.norm(Msym, axis=0)))
    axis = Msym[:, j]
    n = np.linalg.norm(axis)
    if n < 1e-12:
        return theta, np.zeros(3)
    return theta, axis / n


def pose_error(T, T_d, w_rot=W_ROT):
    """(6-vector residual, scalar metric) between pose T and target T_d."""
    T = np.asarray(T, dtype=float)
    T_d = np.asarray(T_d, dtype=float)
    dp = T_d[:3, 3] - T[:3, 3]
    theta, axis = rotation_angle_axis(T_d[:3, :3] @ T[:3, :3].T)
    return (np.concatenate([dp, w_rot * theta * axis]),
            float(np.linalg.norm(dp) + w_rot * theta))
'''
