#!/usr/bin/python
#
#   output_hybrid_python.py --  generated python for the HYBRID method
#
#   The hybrid method answers a robot IKBT cannot solve in closed form by
#   solving a SIMPLIFIED arm -- one DH parameter moved, cheapest in task-space
#   displacement -- and then correcting that answer numerically against the arm
#   the user actually asked about.  Neither half is an answer on its own:  the
#   closed form is exact for the wrong robot, and the numeric step needs a seed
#   good enough to land in the right basin.
#
#   WHAT THE USER GETS, for a hybrid robot called KinovaLite:
#
#       IK_hybrid_KinovaLite.py            <- the top level, both phases
#         imports IK_equationsKinovaLite_d_5_0.py    approximate arm, closed form
#         imports FK_numericKinovaLite_d_5_0.py      approximate arm, FK
#         imports FK_numericKinovaLite.py            TRUE arm, FK *and Jacobian*
#
#   FOUR FILES, NOT ONE.  The hazard of this method is confusing the two arms,
#   and separate files named for the arm they describe make that confusion
#   visible instead of burying both arms in one namespace.  The top level is
#   then small enough to read in one sitting.
#
#   THE TWO ENTRY POINTS, and why it is two and not one:
#
#       ikin_<Robot>_approx(T)      PHASE I.  Every closed-form solution of the
#                                   APPROXIMATE arm for the goal pose T.
#       refine_<Robot>(T, index)    PHASE II.  Damped least squares against the
#                                   TRUE arm's FK, seeded from branch `index`.
#
#   A serial arm's IK branches -- elbow up and down, wrist flipped -- are
#   genuinely different postures, and which one is wanted depends on obstacles,
#   joint limits and where the arm is now, none of which this code knows.  So
#   Phase I enumerates and Phase II commits, with a human or a planner choosing
#   in between.  One call would pick a posture on the user's behalf.
#
#   PHASE I FILTERS.  IKBT enumerates combinations of each unknown's solution
#   branches without discarding the spurious ones, so a returned branch is a
#   candidate, not a solution.  Phase I evaluates the approximate arm's own FK
#   on each branch and keeps those that reproduce T -- which is why the
#   approximate arm's FK is imported and not merely its IK.
#
#   Copyright 2026 University of Washington
#
#   Developed by Blake Hannaford
#   BioRobotics Lab, University of Washington

import os

import sympy as sp

import ikbtbasics.numeric_ik as nik
from ikbtfunctions.output_python import py_identifier


DIR_NAME = os.path.join('CodeGen', 'Python')

#  Everything the generated modules may call.  `abs` is a builtin;  the rest
#  come from math, exactly as the existing IK modules import them.
ALLOWED_FUNCS = {'sin', 'cos', 'tan', 'asin', 'acos', 'atan', 'atan2',
                 'sqrt', 'abs', 'exp', 'log'}

MODULE_HEADER = '''#!/usr/bin/python
#  **WHAT**
#
#  Generated by IKBT.  Do not edit:  regenerate with
#      python3 ikSolver.py **ROBOT**

import numpy as np
from math import sqrt
from math import atan2
from math import cos
from math import sin
from math import acos
from math import asin

pi = np.pi
'''


def expr_py(e):
    '''Python source for one sympy expression, or a raised ValueError.

       sp.pycode() with fully_qualified_modules=False emits exactly the dialect
       the generated modules already support -- bare sin/cos/sqrt/atan2 and a
       bare pi -- so nothing has to be post-processed into shape.

       THE GUARD IS THE POINT.  A function this module cannot promise is
       importable in the generated file (say a Piecewise, or a sympy-only
       special function) would emit source that imports cleanly and then raises
       NameError at the first call, from inside generated code, with no
       indication of which expression was at fault.  Refusing here names it.'''

    src = sp.pycode(e, fully_qualified_modules=False)
    if 'ImmutableDenseMatrix' in src or 'Not supported' in src:
        raise ValueError('cannot express in python: %s' % str(e)[:120])
    for f in e.atoms(sp.Function):
        nm = type(f).__name__
        if nm not in ALLOWED_FUNCS:
            raise ValueError('generated python would need %s(), which the '
                             'module does not import' % nm)
    return src


def _matrix_py(Mx, indent):
    '''A sympy Matrix as a numpy array literal, one row per line.'''

    rows = []
    for i in range(Mx.rows):
        cells = ', '.join(expr_py(Mx[i, j]) for j in range(Mx.cols))
        rows.append('%s[%s]' % (indent + '     ', cells))
    return ('np.array([\n' + ',\n'.join(rows) + '\n' + indent + '    ], '
            'dtype=float)')


###############################################################################
#
#    FK (and Jacobian) for one arm
#

def write_fk_module(M, name, jacobian=True, dirname=DIR_NAME, what=None):
    '''Write FK_numeric<name>.py:  fk_<name>(q), and optionally jacobian_<name>(q).

       FK_numeric, NOT FK_equations.  output_python.output_FK_python_code()
       already owns FK_equations<name>.py -- that is what fkOnly.py writes,
       and it is a different artifact: a module-level dump of the symbolic
       T_06 for reading, with dummy joint values.  This one is a pair of
       numeric callables with the parameters baked in.  Sharing a filename
       would mean whichever ran last silently replaced the other.

       M         a mechanism (Robot.Mech) -- T_06 and J66 come from it
       name      the robot name this arm is;  also the file name
       jacobian  emit the Jacobian too (Phase II needs it, plain FK does not)
       what      one line for the file header, describing which arm this is

       Returns the path written.

       THE PARAMETERS ARE BAKED IN, not left as module globals to be overridden.
       That is the opposite of what IK_equations*.py does, and deliberately:
       these two functions are the definition of "the true arm" that Phase II
       refines against, and a caller who edited a link length here would move
       the target without moving the closed form that seeds it.  Editing the
       robot means regenerating.

       pvals is resolved through numeric_ik.pvals_numeric(), NOT read raw:
       for a non-right-angle alpha kin_cl evaluates sin/cos to a number, but
       falls back to the STRING 'np.cos(al_1)' when the twist's own symbols have
       no numeric value -- and a raw read then leaves al_1 as a free symbol that
       silently becomes a joint argument.'''

    ident = py_identifier(name)
    ndof = nik.dof_of(M)
    syms = nik.joint_symbols(M, ndof)
    pv = nik.pvals_numeric(M)

    T = sp.Matrix(M.T_06).subs(pv)
    #  Only the first ndof columns of J66.  It is stored 6x6 for every robot
    #  and the surplus columns of a short arm are NOT zero -- a padded DH row
    #  still gets a column computed for it -- so handing them to the solver
    #  would let it move joints the arm does not have.
    J = sp.Matrix(M.J66).subs(pv)[:, :ndof] if jacobian else None

    for label, Mx in (('T_06', T), ('J66', J)):
        if Mx is None:
            continue
        extra = sorted(Mx.free_symbols - set(syms), key=str)
        if extra:
            raise ValueError('%s of %s still contains %s -- pvals did not '
                             'resolve every parameter'
                             % (label, name, [str(s) for s in extra]))

    path = os.path.join(dirname, 'FK_numeric%s.py' % name)
    with open(path, 'w') as f:
        hdr = MODULE_HEADER.replace('**ROBOT**', name)
        hdr = hdr.replace('**WHAT**', what or
                          'Forward kinematics for %s' % name)
        print(hdr, file=f)

        print('#  Joint order is the DH CHAIN order, which is what a q vector', file=f)
        print('#  must be in.  It is NOT the order the solver happened to', file=f)
        print('#  solve them in, and it excludes sum-of-angle intermediates.', file=f)
        print('JOINT_NAMES = %r' % [str(s) for s in syms], file=f)
        print('NDOF = %d' % ndof, file=f)
        print('', file=f)

        unpack = ', '.join(str(s) for s in syms)
        print('', file=f)
        print('def fk_%s(q):' % ident, file=f)
        print("    '''q -> 4x4 homogeneous transform of frame 6 in the base frame.'''", file=f)
        print('    %s = [float(v) for v in q]' % unpack, file=f)
        print('    return ' + _matrix_py(T, '    '), file=f)
        print('', file=f)

        if jacobian:
            print('', file=f)
            print('def jacobian_%s(q):' % ident, file=f)
            print("    '''q -> 6 x %d Jacobian, EXPRESSED IN FRAME 6." % ndof, file=f)
            print('', file=f)
            print('       Frame 6, not the base frame:  that is what IKBT', file=f)
            print('       computes and stores as J66.  Rotate it with', file=f)
            print('       jacobian_base() before comparing against a pose', file=f)
            print('       error, which lives in the base frame.', file=f)
            print("    '''", file=f)
            print('    %s = [float(v) for v in q]' % unpack, file=f)
            print('    return ' + _matrix_py(J, '    '), file=f)
            print('', file=f)

    return path


###############################################################################
#
#    The hybrid top level
#

#  The numeric core, emitted verbatim:  damped least squares, and a COPY of
#  ikbtbasics.numeric_ik, because the generated module has to stand on numpy
#  alone and cannot import IKBT.
#
#  A copy is a liability, so it is pinned:  TestSolver024 runs this generated
#  refine() and numeric_ik.solve_numeric() on the same robot from the same seed
#  and requires the same answer.
REFINE_CORE = '''

#############################################################
#
#   Phase II numerics:  damped least squares (Levenberg-Marquardt)
#
#   dq = J'(JJ' + lam^2 I)^-1 e,  with the residual  [dp ; w_rot*theta*axis]
#   and the scalar metric  ||dp|| + w_rot*theta  sharing ONE rotation
#   parameterisation and ONE weight -- so the step and the stopping test agree
#   about what "closer" means.  The Jacobian's rotation rows are scaled by
#   w_rot to match.
#
#   This is a copy of ikbtbasics/numeric_ik.py, which is where it is tested.
#
#############################################################


def rotation_angle_axis(Rerr):
    """(theta, axis) of a rotation matrix, theta in [0, pi]."""
    Rerr = np.asarray(Rerr, dtype=float)
    c = (np.trace(Rerr) - 1.0) / 2.0
    c = min(1.0, max(-1.0, c))
    theta = float(np.arccos(c))
    if theta < 1e-12:
        return 0.0, np.zeros(3)
    if theta < np.pi - 1e-6:
        axis = np.array([Rerr[2, 1] - Rerr[1, 2],
                         Rerr[0, 2] - Rerr[2, 0],
                         Rerr[1, 0] - Rerr[0, 1]]) / (2.0 * np.sin(theta))
        return theta, axis
    #  theta ~ pi: the skew part vanishes, so take the axis from R + I = 2aa'
    Msym = Rerr + np.eye(3)
    j = int(np.argmax(np.linalg.norm(Msym, axis=0)))
    axis = Msym[:, j]
    n = np.linalg.norm(axis)
    if n < 1e-12:
        return theta, np.zeros(3)
    return theta, axis / n


def pose_error(T, T_d, w_rot=W_ROT):
    """(6-vector residual, scalar metric) between pose T and target T_d."""
    T = np.asarray(T, dtype=float)
    T_d = np.asarray(T_d, dtype=float)
    dp = T_d[:3, 3] - T[:3, 3]
    theta, axis = rotation_angle_axis(T_d[:3, :3] @ T[:3, :3].T)
    return (np.concatenate([dp, w_rot * theta * axis]),
            float(np.linalg.norm(dp) + w_rot * theta))


def jacobian_base(T, J66):
    """J_0 = blkdiag(R_06, R_06) . J_66 -- frame 6 into the base frame."""
    R = np.asarray(T)[:3, :3]
    Z = np.zeros((3, 3))
    return np.vstack([np.hstack([R, Z]), np.hstack([Z, R])]) @ np.asarray(J66)


def solve_numeric(fk, jac, q0, T_d, w_rot=W_ROT, tol=1e-9, max_iter=100,
                  lam0=1e-3, lam_min=1e-12, lam_max=1e12):
    """Refine seed q0 until fk(q) matches T_d.  Returns a dict.

       Never raises on a bad step:  a singular solve or a non-finite FK is a
       REJECTED step, which raises lam and tries again.  That is the whole
       point of damping -- at a singularity an undamped Newton step does not
       exist, and this must degrade rather than fail."""
    q = np.array(q0, dtype=float).flatten()
    lam = float(lam0)
    I6 = np.eye(6)
    W = np.diag([1.0, 1.0, 1.0, w_rot, w_rot, w_rot])

    def measure(qq):
        T = fk(qq)
        if not np.all(np.isfinite(T)):
            return None, np.inf
        return pose_error(T, T_d, w_rot=w_rot)

    e, m = measure(q)
    history = [m]
    reason = 'max_iter'

    for _ in range(max_iter):
        if m <= tol:
            reason = 'converged'
            break
        T = fk(q)
        try:
            J = W @ jacobian_base(T, jac(q))
            A = J @ J.T + (lam ** 2) * I6
            dq = J.T @ np.linalg.solve(A, e)
        except np.linalg.LinAlgError:
            lam = min(lam * 10.0, lam_max)
            if lam >= lam_max:
                reason = 'lam_max'
                break
            continue
        if not np.all(np.isfinite(dq)):
            lam = min(lam * 10.0, lam_max)
            if lam >= lam_max:
                reason = 'lam_max'
                break
            continue
        q_try = q + dq
        e_try, m_try = measure(q_try)
        if m_try < m:
            q, e, m = q_try, e_try, m_try
            lam = max(lam / 3.0, lam_min)
        else:
            lam = min(lam * 3.0, lam_max)
            if lam >= lam_max:
                reason = 'lam_max'
                break
        history.append(m)

    return {'q': q, 'metric': m, 'iterations': len(history) - 1,
            'converged': bool(m <= tol),
            'reason': reason if m > tol else 'converged',
            'history': history}
'''


def write_hybrid_top(M_true, true_name, derived_name, edits_text, cost_text,
                     dirname=DIR_NAME):
    '''Write IK_hybrid_<true_name>.py -- the two-phase top level.

       M_true        the TRUE arm's mechanism, for w_rot and the joint names
       true_name     the robot the user asked about
       derived_name  the simplified arm that was actually solved in closed form
       edits_text    human-readable list of the DH changes ('d_5: 57 -> 0')
       cost_text     the task-space cost of those changes, or ''

       Returns the path written.'''

    ident = py_identifier(true_name)
    dident = py_identifier(derived_name)
    ndof = nik.dof_of(M_true)
    jnames = [str(s) for s in nik.joint_symbols(M_true, ndof)]

    #  w_rot HAS NO CORRECT DEFAULT, so it is baked in per robot rather than
    #  defaulted in the numerics.  BH's metric is ||dp|| + (1 m)*theta, but
    #  nothing records a model's units and they are not consistent across the
    #  robot set -- Puma is in metres (a_2 = 0.432), KinovaLite in millimetres
    #  (l_2 = 280).  w_rot_for() sidesteps that with a unit-free choice: one
    #  characteristic arm length per radian, which behaves the same on both.
    w_rot = nik.w_rot_for(M_true, ndof)

    path = os.path.join(dirname, 'IK_hybrid_%s.py' % true_name)
    with open(path, 'w') as f:
        hdr = MODULE_HEADER.replace('**ROBOT**', true_name)
        hdr = hdr.replace('**WHAT**',
                          'HYBRID inverse kinematics for %s' % true_name)
        print(hdr, file=f)

        print('import os', file=f)
        print('import sys', file=f)
        print('', file=f)
        print('#  Import our siblings by location, so this works however the', file=f)
        print('#  caller happens to have arranged sys.path.', file=f)
        print('sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))', file=f)
        print('', file=f)
        print('import IK_equations%s as approx_ik    # approximate arm, closed form'
              % derived_name, file=f)
        print('import FK_numeric%s as approx_fk      # approximate arm, FK'
              % derived_name, file=f)
        print('import FK_numeric%s as true_fk        # TRUE arm, FK and Jacobian'
              % true_name, file=f)
        print('', file=f)

        print('''
#############################################################
#
#   READ THIS FIRST.
#
#   %s could not be solved in closed form.  What is solved here
#   is a SIMPLIFIED arm, %s, obtained by changing
#
#       %s%s
#
#   The closed form is EXACT for that simplified arm and only APPROXIMATE for
#   %s.  Phase II corrects it, by damped least squares against the
#   true arm's own forward kinematics.  A joint vector that has not been
#   through Phase II does not put the real robot at the pose you asked for.
#
#############################################################
''' % (true_name, derived_name, edits_text,
       ('   (%s)' % cost_text) if cost_text else '', true_name), file=f)

        print('TRUE_ROBOT      = %r' % true_name, file=f)
        print('APPROXIMATE_ARM = %r' % derived_name, file=f)
        print('DH_CHANGES      = %r' % edits_text, file=f)
        print('JOINT_NAMES     = %r' % jnames, file=f)
        print('NDOF            = %d' % ndof, file=f)
        print('', file=f)
        print('#  One characteristic arm length per radian:  the weight that puts', file=f)
        print('#  position error and orientation error in comparable units.  It is', file=f)
        print('#  baked in because nothing records a model\'s units and they are', file=f)
        print('#  not consistent across the robot set:  some arms are in metres,', file=f)
        print('#  some in millimetres.  This value is in the DH table\'s units.', file=f)
        print('W_ROT           = %r' % float(w_rot), file=f)
        print('', file=f)
        print('#  A Phase I branch is kept when its own arm reproduces the goal', file=f)
        print('#  pose this closely.  Loose enough to survive float noise, tight', file=f)
        print('#  enough that a spurious branch cannot pass.', file=f)
        print('APPROX_TOL      = 1e-6', file=f)

        print(REFINE_CORE, file=f)

        #####################################################################
        #  PHASE I
        #####################################################################
        print('''
#############################################################
#
#   PHASE I -- every closed-form solution of the APPROXIMATE arm
#
#############################################################


def ikin_**IDENT**_approx(T, filter_spurious=True):
    """Goal pose T (4x4) -> list of joint vectors for the APPROXIMATE arm.

       Each entry is NDOF floats in JOINT_NAMES order.  Returns [] when the
       closed form reports the pose unreachable.

       filter_spurious=True drops branches that do not actually reach T.  IKBT
       enumerates combinations of each unknown's solution branches and does not
       discard the ones that do not satisfy the original equations, so a
       returned branch is a CANDIDATE.  Checking each against the approximate
       arm's own FK is cheap and removes them;  pass False to see the raw list.

       These are seeds, not answers.  Feed the index you want to
       refine_**IDENT**()."""

    sols = approx_ik.ikin_**DIDENT**(np.matrix(np.asarray(T, dtype=float)))
    if sols is False:
        return []

    out = []
    for row in sols:
        q = [float(v) for v in row]
        if not filter_spurious:
            out.append(q)
            continue
        try:
            Terr = np.asarray(approx_fk.fk_**DIDENT**(q), dtype=float)
        except Exception:
            continue
        if np.all(np.isfinite(Terr)) and \\
                np.max(np.abs(Terr - np.asarray(T, dtype=float))) < APPROX_TOL:
            out.append(q)
    return out
'''.replace('**IDENT**', ident).replace('**DIDENT**', dident), file=f)

        #####################################################################
        #  PHASE II
        #####################################################################
        print('''
#############################################################
#
#   PHASE II -- correct one chosen branch against the TRUE arm
#
#############################################################


def refine_**IDENT**(T, index=0, seeds=None, tol=1e-9, max_iter=100):
    """Numerically correct one Phase I branch against the TRUE arm's FK.

           T       the goal pose, the same 4x4 given to Phase I
           index   WHICH Phase I branch to start from
           seeds   an explicit branch list, if you already have Phase I's

       Returns the solve_numeric() dict -- q, metric, iterations, converged,
       reason, history -- with 'index' and 'seed' added.

       WHY YOU CHOOSE THE INDEX.  The branches are different postures (elbow
       up or down, wrist flipped), not different spellings of one answer, and
       which is wanted depends on obstacles, joint limits, and where the arm is
       now.  None of that is known here.  Refinement stays in the basin of the
       seed it is given, so the choice of index is the choice of posture.

       converged=False is a real answer, not an error:  the true arm may not
       reach this pose at all, or may reach it only from a different branch.
       Check it."""

    if seeds is None:
        seeds = ikin_**IDENT**_approx(T)
    if not seeds:
        return {'q': None, 'converged': False, 'metric': float('inf'),
                'iterations': 0, 'reason': 'no approximate solution',
                'history': [], 'index': index, 'seed': None}
    if not (0 <= index < len(seeds)):
        raise IndexError('branch %d of %d -- Phase I returned %d branches'
                         % (index, len(seeds), len(seeds)))

    seed = seeds[index]
    T_d = np.asarray(T, dtype=float)
    r = solve_numeric(true_fk.fk_**IDENT**, true_fk.jacobian_**IDENT**,
                      seed, T_d, w_rot=W_ROT, tol=tol, max_iter=max_iter)
    r['index'] = index
    r['seed'] = seed
    return r


def refine_all_**IDENT**(T, tol=1e-9, max_iter=100):
    """Phase II from EVERY Phase I branch.  Returns a list of result dicts.

       Convenience for the caller who wants to see which postures actually
       survive on the true arm before choosing one."""

    seeds = ikin_**IDENT**_approx(T)
    return [refine_**IDENT**(T, i, seeds=seeds, tol=tol, max_iter=max_iter)
            for i in range(len(seeds))]
'''.replace('**IDENT**', ident), file=f)

        #####################################################################
        #  demo
        #####################################################################
        print('''
if __name__ == '__main__':
    #  Round trip:  pick joints, build the pose they produce on the TRUE arm,
    #  and see whether the two phases recover them.
    q_demo = [0.4, -0.6, 0.7, 0.9, -0.5, 0.3][:NDOF]
    T_goal = true_fk.fk_**IDENT**(q_demo)

    print('')
    print('  %s -- hybrid IK via %s' % (TRUE_ROBOT, APPROXIMATE_ARM))
    print('  approximated by: %s' % DH_CHANGES)
    print('')

    branches = ikin_**IDENT**_approx(T_goal)
    print('  PHASE I: %d usable branch(es) from the approximate arm' % len(branches))
    for i, q in enumerate(branches):
        print('     [%d]  %s' % (i, ' '.join('%8.4f' % v for v in q)))

    print('')
    print('  PHASE II: refined against the true arm')
    for r in refine_all_**IDENT**(T_goal):
        if r['q'] is None:
            print('     [%d]  no seed' % r['index'])
            continue
        print('     [%d]  %s   metric %.2e  %2d iters  %s'
              % (r['index'], ' '.join('%8.4f' % v for v in r['q']),
                 r['metric'], r['iterations'], r['reason']))
    print('')
'''.replace('**IDENT**', ident), file=f)

    return path


#####################################################################
#
#   Test code
#

import unittest


class TestSolver024(unittest.TestCase):
    '''The hybrid code generator.

       Two properties, and both are about a COPY staying honest.  This module
       emits kinematics and an algorithm into a standalone file;  nothing else
       in IKBT then reads that file, so an error in it is invisible to every
       other test.  These two compare the emitted thing against the tested
       thing it was copied from.'''

    def setUp(self):
        print('\n\n===============  Test hybrid code generator  =====================')
        return

    def runTest(self):
        self.test_hgA_generated_fk_matches_the_library()
        self.test_hgB_generated_refine_matches_the_library()
        self.test_hgC_expr_py_refuses_what_it_cannot_emit()

    #  Puma, because it solves exactly and its pickle is always warm.  The
    #  generator does not care that Puma is not a hybrid robot:  what is under
    #  test is the emitted kinematics, not which branch produced them.
    def puma(self):
        import io as _io
        import contextlib as _cl
        from ikbtfunctions.ik_robots import robot_params
        from ikbtbasics.ik_classes import kinematics_pickle

        buf = _io.StringIO()
        with _cl.redirect_stdout(buf):
            dh, vv, params, pvals, unks = robot_params('Puma')
            M, R, unks = kinematics_pickle('Puma', dh, params, pvals, vv,
                                           unks, False)
        return M

    def test_hgA_generated_fk_matches_the_library(self):
        '''The EMITTED fk/jacobian must agree with numeric_ik's lambdified ones.

           Phase II refines against the generated FK, so if that FK is not the
           true arm's, the method converges confidently on the wrong pose --
           and every check downstream that uses the same generated FK would
           agree with it.  This is the one comparison against an independent
           construction of the same kinematics.'''
        import importlib.util
        import tempfile
        import numpy as np

        fs = ' hybrid codegen FK FAIL'
        M = self.puma()

        with tempfile.TemporaryDirectory() as d:
            path = write_fk_module(M, 'Puma', jacobian=True, dirname=d)
            spec = importlib.util.spec_from_file_location('gen_fk_puma', path)
            gen = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(gen)

            fk_ref = nik.fk_callable(M)
            jac_ref = nik.jacobian_callable(M)

            self.assertEqual(gen.JOINT_NAMES,
                             [str(s) for s in nik.joint_symbols(M)],
                             fs + ' (joint order differs from numeric_ik)')

            rng = np.random.default_rng(20260902)
            for _ in range(8):
                q = list(rng.uniform(-2.0, 2.0, gen.NDOF))
                dT = np.max(np.abs(np.asarray(gen.fk_Puma(q), dtype=float)
                                   - np.asarray(fk_ref(q), dtype=float)))
                dJ = np.max(np.abs(np.asarray(gen.jacobian_Puma(q), dtype=float)
                                   - np.asarray(jac_ref(q), dtype=float)))
                self.assertLess(dT, 1e-9, fs + ' (FK differs by %g)' % dT)
                self.assertLess(dJ, 1e-9, fs + ' (Jacobian differs by %g)' % dJ)

    def test_hgB_generated_refine_matches_the_library(self):
        '''REFINE_CORE must solve identically to numeric_ik.solve_numeric().

           The generated module cannot import ikbtbasics -- it stands on numpy
           alone -- so the damped-least-squares loop is emitted as a copy of
           the library one.  A copy that drifts is worse than no copy:  the
           library stays green while what ships to users quietly stops
           converging.  This runs both on the same problem from the same seed
           and requires the same answer.'''
        import numpy as np

        fs = ' hybrid codegen refine FAIL'
        M = self.puma()
        fk = nik.fk_callable(M)
        jac = nik.jacobian_callable(M)
        ndof = nik.dof_of(M)
        w_rot = 1.0                      # Puma is in metres

        #  Exec the emitted source in a bare namespace.  numpy and W_ROT are
        #  all the generated module gives it, so that is all it gets here --
        #  a missing name would otherwise be masked by this file's globals.
        ns = {'np': np, 'W_ROT': w_rot}
        exec(REFINE_CORE, ns)
        self.assertIn('solve_numeric', ns, fs + ' (REFINE_CORE emitted no solver)')

        q_true = np.array([0.4, -0.6, 0.7, 0.9, -0.5, 0.3][:ndof])
        T_d = np.asarray(fk(q_true), dtype=float)

        rng = np.random.default_rng(24)
        for k in range(4):
            seed = list(q_true + rng.uniform(-0.3, 0.3, ndof))
            ref = nik.solve_numeric(fk, jac, seed, T_d, w_rot=w_rot)
            got = ns['solve_numeric'](fk, jac, seed, T_d, w_rot=w_rot)

            self.assertEqual(bool(got['converged']), bool(ref['converged']),
                             fs + ' (seed %d: converged differs)' % k)
            self.assertEqual(got['iterations'], ref['iterations'],
                             fs + ' (seed %d: iteration count differs, %d vs %d)'
                             % (k, got['iterations'], ref['iterations']))
            dq = float(np.max(np.abs(np.asarray(got['q']) - np.asarray(ref['q']))))
            self.assertLess(dq, 1e-12,
                            fs + ' (seed %d: answers differ by %g)' % (k, dq))

    def test_hgC_expr_py_refuses_what_it_cannot_emit(self):
        '''A function the generated module does not import must RAISE here.

           Emitting it instead would produce a file that imports cleanly and
           then dies with a NameError inside generated code, naming neither the
           expression nor the robot.'''
        fs = ' hybrid codegen guard FAIL'
        x = sp.Symbol('th_1')

        self.assertEqual(expr_py(sp.cos(x) + 2), 'cos(th_1) + 2',
                         fs + ' (ordinary expression did not emit)')
        with self.assertRaises(ValueError, msg=fs + ' (accepted a sympy-only '
                               'function the module cannot call)'):
            expr_py(sp.sinh(x))


def run_test():
    t = TestSolver024()
    t.setUp()
    t.runTest()
    print('\n\n            hybrid code generator PASSES\n\n')


if __name__ == '__main__':
    unittest.main()
