#!/usr/bin/python
#
#   output_cpp_common.py --  generated-C++ pieces more than one method needs
#
#   The twin of output_numeric_common.py, and derived from it row by row:  how
#   a sympy expression becomes C++, what a generated translation unit may
#   include, how a robot's parameters are declared, and how the hand-written
#   numerics in Cpp_src/ get into the file.
#
#   THE PYTHON GENERATOR IS THE SPECIFICATION.  Every function here has a named
#   counterpart in output_python.py or output_numeric_common.py and is expected
#   to produce the same numbers;  scripts/cpp_expr_check.py and
#   scripts/cpp_closed_loop_check.py assert that rather than assume it.
#
#   Copyright 2026 University of Washington
#
#   Developed by Blake Hannaford
#   BioRobotics Lab, University of Washington

import os
import re

import sympy as sp

import ikbtbasics.numeric_ik as nik


DIR_NAME = os.path.join('CodeGen', 'Cpp')

#  Cpp_src/ IS SOURCE, on the LaTex_src/ precedent:  hand-written C++ that the
#  generator reads and inlines, so a generated .cpp is self-contained.  It is
#  deliberately not under CodeGen/, which cleanCodeGenOutput wipes.
SRC_DIR = 'Cpp_src'

#  Everything a generated module may call.  The SAME SET as
#  output_numeric_common.ALLOWED_FUNCS -- the point of the whitelist is that
#  the two languages accept exactly the same expressions, so that an equation
#  IKBT can emit as python it can also emit as C++.  sympy's C++ printer maps
#  each of these into <cmath>.
ALLOWED_FUNCS = {'sin', 'cos', 'tan', 'asin', 'acos', 'atan', 'atan2',
                 'sqrt', 'Abs', 'exp', 'log'}

#  The banner.  MODULE_HEADER's twin;  **WHAT** and **ROBOT** substitute the
#  same way.
FILE_HEADER = '''//
//  **WHAT**
//
//  Generated by IKBT.  Do not edit:  regenerate with
//      python3 ikSolver.py **ROBOT**
//
//  Build:
//      g++ -std=c++11 -O2 -c **FILE**
//  Run its self-test:
//      g++ -std=c++11 -O2 -DIKBT_MAIN **FILE** -o ik_test -lm && ./ik_test
//
'''

#  What a parameter with no numerical value is emitted as.  A DELIBERATE
#  COMPILE STOP:  g++ says "'XXXXX' was not declared in this scope" and names
#  the line, so a missing link length cannot be silently defaulted to
#  something wrong.  Documented in CodeGen/HOWTO.txt.
#
#  It used to fire for EVERY parameter, including the robots whose pvals are
#  complete -- 25 of 26 generated files could not be compiled, which is why
#  none of them had ever been checked.  Now it fires only where python would
#  also have written XXXXX.
NO_VALUE = 'XXXXX'


def cpp_identifier(name):
    """A robot name turned into a valid C++ identifier.

       py_identifier()'s twin, and the same rules apply for the same reason:
       'C-Arm' is a legal robot name, a legal file name and a legal LaTeX
       label, but 'ikin_C-Arm' is a subtraction."""

    ident = re.sub(r'\W', '_', str(name))
    if ident and ident[0].isdigit():
        ident = '_' + ident          # an identifier may not start with a digit
    return ident


def expr_cpp(e):
    '''C++ source for one sympy expression, or a raised ValueError.

       expr_py()'s twin, and the reason the old generator's defects are gone
       rather than fixed:  sp.cxxcode is a real C++ printer, so

           (Px - a_1)**2   ->  std::pow(Px - a_1, 2)
           sin(x)**2       ->  std::pow(std::sin(x), 2)
           atan2(y,x)+pi/2 ->  std::atan2(y, x) + M_PI_2
           Abs(x)          ->  std::fabs(x)

       all come out right.  What it replaced was a two-line regex over the
       printed python that handled `x**2` and `sin(x)**2` and silently left
       `(Px - a_1)**2` as invalid C++ -- which is what Arm_3 and UR5 shipped.

       It also prints every Rational as `(1.0/3.0)`, so there is no integer
       division hazard, and every Float at 17 significant digits, so a baked
       parameter keeps the value python had.'''

    src = sp.cxxcode(sp.sympify(e), standard='c++11')
    if 'Not supported' in src or '// Not supported' in src:
        raise ValueError('cannot express in C++: %s' % str(e)[:120])
    for f in sp.sympify(e).atoms(sp.Function):
        nm = type(f).__name__
        if nm not in ALLOWED_FUNCS:
            raise ValueError('generated C++ would need %s(), which is not in '
                             'the shared whitelist' % nm)
    return src


def read_src(basename):
    '''One Cpp_src/ header, verbatim, for inlining into a generated file.

       output_latex.py inlines LaTex_src/IK_preamble.tex exactly this way and
       for exactly this reason:  the emitted artifact has to stand alone, but
       the material it stands on should be real source that can be read,
       compiled and tested on its own.

       The headers carry classic include guards rather than `#pragma once`,
       which g++ warns about ("#pragma once in main file") once inlined.'''

    path = os.path.join(SRC_DIR, basename)
    with open(path) as f:
        return f.read()


def inline_src(names):
    """Several Cpp_src/ headers, concatenated in dependency order, ready to be
       pasted into a generated file.

       The `#include "ikbt_*.h"` lines are STRIPPED.  Once inlined there is no
       ikbt_types.h next to the generated file for them to find, and the whole
       point of inlining is that there does not have to be.  The classic
       include guards in each header make the concatenation safe however often
       a header appears -- so a generated .cpp may inline these AND include a
       generated FK header that inlines some of them again.

       Caller supplies the order;  these are four small files and a dependency
       solver for them would be more machinery than the problem.  The order
       that works is types, linalg, pose_error, dls.
    """

    out = []
    for nm in names:
        text = read_src(nm)
        kept = [ln for ln in text.split('\n')
                if not re.match(r'\s*#include\s+"ikbt_', ln)]
        out.append('\n'.join(kept))
    return '\n'.join(out)


def file_header(what, robot, filename):
    '''The comment banner at the top of a generated .cpp.'''

    hdr = FILE_HEADER.replace('**WHAT**', what)
    hdr = hdr.replace('**ROBOT**', str(robot))
    return hdr.replace('**FILE**', filename)


###############################################################################
#
#    Robot parameters
#

def param_values(M, params=None):
    '''{Symbol: float} for the parameters that HAVE a value, as python bakes them.

       Mech.params, NOT Robot.params, for the same reason output_python.py
       gives:  Mech.params also carries the ca_i / sa_i that
       forward_kinematics() invented for a twist angle that is not a multiple
       of 90 degrees, and those appear in the equations.  Here an omission is a
       COMPILE error rather than a runtime one, since C++ needs every name
       declared -- which makes it the better of the two failures, but only
       once the values that DO exist are actually emitted.

       pvals_numeric() resolves the 'np.cos(al_1)' string fallbacks that
       kin_cl still writes for an alpha it cannot evaluate.  If it cannot
       resolve the lot, fall back to the raw dict rather than lose the
       parameters that were fine.'''

    try:
        return nik.pvals_numeric(M)
    except Exception:
        out = {}
        for k, v in (M.pvals or {}).items():
            if isinstance(v, str):
                continue
            try:
                out[sp.sympify(k)] = float(v)
            except (TypeError, ValueError):
                pass
        return out


def param_decls(M, params=None, indent=''):
    '''`const double a_2 = 0.432;` for every declared parameter.

       NAMESPACE SCOPE, not inside ikin().  That mirrors python, where the
       parameters are module-level so a caller can inspect or override them;
       the old C++ declared them as locals inside the function, where nothing
       outside could see them.

       `const`, because the python module's values come from the robot
       definition and overriding one at runtime means you have a different
       robot.  A user editing the file to supply an XXXXX edits a const.'''

    decl = list(params if params is not None
                else (getattr(M, 'params', None) or []))
    pv = param_values(M)

    lines = []
    missing = []
    for p in decl:
        key = sp.sympify(p)
        if key in pv:
            lines.append('%sconst double %s = %s;'
                         % (indent, str(p), expr_cpp(sp.Float(pv[key], 17))))
        else:
            missing.append(str(p))
            lines.append('%sconst double %s = %s;   // USER MUST supply a '
                         'numerical value here' % (indent, str(p), NO_VALUE))
    return '\n'.join(lines), missing


###############################################################################
#
#    Matrices
#

def matrix_cpp(Mx, var, indent='    '):
    '''A sympy Matrix as C++ statements filling `var`, one element per line.

       _matrix_py()'s twin.  An element at a time rather than a braced
       initialiser:  the expressions are long (Puma's T_06 runs to hundreds of
       characters), and one element per line is what makes a compiler
       diagnostic point at something.'''

    lines = []
    for i in range(Mx.rows):
        for j in range(Mx.cols):
            lines.append('%s%s[%d][%d] = %s;'
                         % (indent, var, i, j, expr_cpp(Mx[i, j])))
    return '\n'.join(lines)


def joint_unpack_cpp(syms, indent='    '):
    '''`const double th_1 = q[0];` ... -- the twin of python's tuple unpack.'''

    return '\n'.join('%sconst double %s = q[%d];' % (indent, str(s), i)
                     for i, s in enumerate(syms))


def pose_unpack_cpp(indent='    '):
    '''r_11..r_33, Px, Py, Pz out of a Mat4.

       The same twelve names the equations are written in, and the same
       ROW-MAJOR reading python does:  T[0,3] is Px in both.'''

    lines = []
    for i in range(3):
        for j in range(3):
            lines.append('%sconst double r_%d%d = T[%d][%d];'
                         % (indent, i + 1, j + 1, i, j))
    for k, nm in enumerate(('Px', 'Py', 'Pz')):
        lines.append('%sconst double %s = T[%d][3];' % (indent, nm, k))

    #  Not every arm's solution mentions all twelve -- a wrist uses no
    #  position at all -- and an unused const is a -Wunused-variable warning.
    #  Declaring them unconditionally keeps the block identical for every
    #  robot, which is worth more than the warnings cost to silence.
    names = ['r_%d%d' % (i + 1, j + 1) for i in range(3) for j in range(3)]
    names += ['Px', 'Py', 'Pz']
    lines.append('%s(void) %s;' % (indent, '; (void) '.join(names)))
    return '\n'.join(lines)


def name_table_cpp(names, var, indent=''):
    '''`const char* const JOINT_NAMES[] = {"th_1", ...};` plus its length.

       The twin of python's JOINT_NAMES list.  C has no way to hand back a
       name with a value, so the ORDER is the contract and this table is what
       documents it.'''

    if not names:
        #  A zero-length array is ill-formed in C++;  one empty slot is not.
        return ('%sconst char* const %s[] = {""};\n%sconst int N_%s = 0;'
                % (indent, var, indent, var))
    body = ', '.join('"%s"' % n for n in names)
    return ('%sconst char* const %s[] = {%s};\n%sconst int N_%s = %d;'
            % (indent, var, body, indent, var, len(names)))


###############################################################################
#
#    FK (and Jacobian) for one arm
#

def write_fk_module_cpp(M, name, jacobian=True, dirname=DIR_NAME, what=None):
    '''Write FK_numeric<name>.h -- fk_<name>(q), and optionally jacobian_<name>(q).

       The twin of output_numeric_common.write_fk_module(), argument for
       argument, with the same guard and the same reasoning:

       FK_numeric, NOT FK_equations.  output_python.output_FK_python_code()
       owns FK_equations<name>, which is a readable dump of the symbolic T_06
       with dummy joint values -- a different artifact.  Sharing the name would
       mean whichever ran last silently replaced the other.

       A HEADER, not a .cpp, because something else includes it.  The python
       twin is a module the hybrid and one-variable modules import as a
       sibling;  `#include "FK_numeric<name>.h"` searches the including file's
       own directory first, so the two arrangements are the same arrangement.
       Everything is `inline`, so several translation units may include it.

       It still inlines ikbt_types.h, as every generated file does.  The
       include guards make that safe however many of them end up in one
       translation unit.

       THE PARAMETERS ARE BAKED IN, not left as overridable globals -- the
       opposite of IK_equations*, and deliberately: these functions are the
       definition of "the true arm" that Phase II refines against.

       Only the first ndof columns of J66.  It is stored 6x6 for every robot
       and the surplus columns of a short arm are NOT zero -- a padded DH row
       still gets a column computed for it -- so handing them to the solver
       would let it move joints the arm does not have.

       Returns the path written.'''

    ident = cpp_identifier(name)
    ndof = M.ndof
    syms = nik.joint_symbols(M, ndof)
    pv = nik.pvals_numeric(M)

    T = sp.Matrix(M.T_06).subs(pv)
    J = sp.Matrix(M.J66).subs(pv)[:, :ndof] if jacobian else None

    for label, Mx in (('T_06', T), ('J66', J)):
        if Mx is None:
            continue
        extra = sorted(Mx.free_symbols - set(syms), key=str)
        if extra:
            raise ValueError('%s of %s still contains %s -- pvals did not '
                             'resolve every parameter'
                             % (label, name, [str(s) for s in extra]))

    filename = 'FK_numeric%s.h' % name
    path = os.path.join(dirname, filename)
    guard = 'IKBT_FK_NUMERIC_%s_H' % ident.upper()

    with open(path, 'w') as f:
        print(file_header(what or 'Forward kinematics for %s' % name,
                          name, filename), file=f)
        print('#ifndef %s' % guard, file=f)
        print('#define %s' % guard, file=f)
        print('', file=f)
        print(read_src('ikbt_types.h'), file=f)
        print('', file=f)
        print('namespace ikbt {', file=f)
        print('', file=f)

        print('//  Joint order is the DH CHAIN order, which is what a q vector', file=f)
        print('//  must be in.  It is NOT the order the solver happened to', file=f)
        print('//  solve them in, and it excludes sum-of-angle intermediates.', file=f)
        print(name_table_cpp([str(s) for s in syms],
                             'FK_JOINT_NAMES_%s' % ident), file=f)
        print('const int NDOF_%s = %d;' % (ident, ndof), file=f)
        print('', file=f)

        print('//  q -> 4x4 homogeneous transform of frame 6 in the base frame.', file=f)
        print('inline Mat4 fk_%s(const JointVec &q)' % ident, file=f)
        print('{', file=f)
        print(joint_unpack_cpp(syms), file=f)
        print('    Mat4 T;', file=f)
        print(matrix_cpp(T, 'T'), file=f)
        print('    return T;', file=f)
        print('}', file=f)
        print('', file=f)

        if jacobian:
            print('//  q -> 6 x %d Jacobian, EXPRESSED IN FRAME 6.' % ndof, file=f)
            print('//', file=f)
            print('//  Frame 6, not the base frame:  that is what IKBT computes', file=f)
            print('//  and stores as J66.  Rotate it with jacobian_base() before', file=f)
            print('//  comparing against a pose error, which lives in the base', file=f)
            print('//  frame.', file=f)
            print('inline Matrix jacobian_%s(const JointVec &q)' % ident, file=f)
            print('{', file=f)
            print(joint_unpack_cpp(syms), file=f)
            print('    Matrix J(6, std::vector<double>(%d, 0.0));' % ndof, file=f)
            print(matrix_cpp(J, 'J'), file=f)
            print('    return J;', file=f)
            print('}', file=f)
            print('', file=f)

        print('}   // namespace ikbt', file=f)
        print('', file=f)
        print('#endif   // %s' % guard, file=f)

    return path
