#!/usr/bin/python
#
#   output_cpp_common.py --  the C++ generation pieces all three methods share
#
#   Printing a sympy expression as C++, the #include lines a generated file
#   needs, declaring a robot's parameters, and writing out FK and the Jacobian.
#
#   Every function here mirrors one in output_python.py or
#   output_numeric_common.py and must produce the same numbers.  The python
#   generator is the specification;  scripts/cpp_expr_check.py and
#   scripts/cpp_closed_loop_check.py check that the two really do agree.
#
#   Copyright 2026 University of Washington
#
#   Developed by Blake Hannaford
#   BioRobotics Lab, University of Washington

import os
import re
from io import StringIO as _StringIO

import sympy as sp

import ikbtbasics.numeric_ik as nik


#  The PARENT of the generated directories.  Each robot gets its own
#  subdirectory under this one -- see robot_dir().
DIR_NAME = os.path.join('CodeGen', 'Cpp')

#  Cpp_src/ holds hand-written C++ shipped with IKBT, so it sits outside
#  CodeGen/, which cleanCodeGenOutput wipes.
#
#  Absolute, and resolved against THIS MODULE rather than the working
#  directory.  Generated output belongs wherever the user ran IKBT from, but
#  Cpp_src/ is always in the same place;  a test that chdir's would not find
#  it by a relative path.
SRC_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                       'Cpp_src')

#  Everything a generated file may call.  The same set as
#  output_numeric_common.ALLOWED_FUNCS, so that any equation IKBT can write as
#  python it can also write as C++.  sympy's C++ printer maps each into
#  <cmath>.
ALLOWED_FUNCS = {'sin', 'cos', 'tan', 'asin', 'acos', 'atan', 'atan2',
                 'sqrt', 'Abs', 'exp', 'log'}

#  The banner at the top of a generated file.  file_header() substitutes
#  **WHAT**, **ROBOT** and **FILE**.
FILE_HEADER = '''//
//  **WHAT**
//
//  Generated by IKBT.  Do not edit:  regenerate with
//      python3 ikSolver.py **ROBOT**
//
//  Build -- no -I, from any working directory.  This file reaches
//  Cpp_src/ and its own siblings by paths relative to ITSELF, so keep
//  this directory intact and where it is relative to Cpp_src/.
//      g++ -std=c++11 -O2 -c **FILE**
//  Run its self-test:
//      g++ -std=c++11 -O2 -DIKBT_MAIN **FILE** -o ik_test -lm && ./ik_test
//
'''

#  What a parameter with no numerical value is emitted as.  A deliberate
#  compile stop:  g++ says "'XXXXX' was not declared in this scope" and names
#  the line, so a missing link length cannot be quietly defaulted to something
#  wrong.  Documented in CodeGen/HOWTO.txt.
NO_VALUE = 'XXXXX'


def cpp_identifier(name):
    """A robot name turned into a valid C++ identifier.

       The twin of py_identifier().  'C-Arm' is a legal robot name and a legal
       file name, but 'ikin_C-Arm' would compile as a subtraction."""

    ident = re.sub(r'\W', '_', str(name))
    if ident and ident[0].isdigit():
        ident = '_' + ident          # an identifier may not start with a digit
    return ident


def expr_cpp(e):
    '''C++ source for one sympy expression, or a raised ValueError.

       expr_py()'s twin.  sp.cxxcode is a real C++ printer, so

           (Px - a_1)**2   ->  std::pow(Px - a_1, 2)
           sin(x)**2       ->  std::pow(std::sin(x), 2)
           atan2(y,x)+pi/2 ->  std::atan2(y, x) + M_PI_2
           Abs(x)          ->  std::fabs(x)

       It prints every Rational as `(1.0/3.0)`, so 1/3 cannot become integer
       division, and every Float at 17 significant digits, so a baked-in
       parameter keeps exactly the value python had.'''

    src = sp.cxxcode(sp.sympify(e), standard='c++11')
    if 'Not supported' in src or '// Not supported' in src:
        raise ValueError('cannot express in C++: %s' % str(e)[:120])
    for f in sp.sympify(e).atoms(sp.Function):
        nm = type(f).__name__
        if nm not in ALLOWED_FUNCS:
            raise ValueError('generated C++ would need %s(), which is not in '
                             'the shared list of allowed functions' % nm)
    return src


def read_src(basename):
    '''One Cpp_src/ header, verbatim.

       For reading a header in order to check it:  the tests compile each one
       on its own, which is why Cpp_src/ holds real files rather than string
       literals in this module.  Generated files reach the headers by the
       relative #include that src_includes() writes.'''

    path = os.path.join(SRC_DIR, basename)
    with open(path) as f:
        return f.read()


def src_includes(names, dirname):
    """`#include` lines for the Cpp_src/ headers a generated file needs.

       There is ONE copy of the shared numerics for the whole package, so a
       fix to ikbt_search.h reaches every robot already generated, without
       regenerating anything.

       The path is computed with relpath rather than spelled out.  From a
       robot directory it comes out as ../../../Cpp_src/ikbt_types.h, but
       scripts/cpp_closed_loop_check.py stages generated files into a
       temporary directory at no fixed depth, where a hardcoded `../../../`
       would miss.

       `#include "..."` resolves against the including file's own directory,
       so a generated file needs no -I:
           g++ -std=c++11 -O2 file.cpp -o x -lm
       The headers include each other the same way and are siblings, so they
       need no handling here either.

       The caller supplies the order;  with five small headers a dependency
       solver would be more machinery than the problem.  The order that works
       is types, linalg, pose_error, dls, search.
    """

    rel = os.path.relpath(SRC_DIR, os.path.abspath(dirname))
    return '\n'.join('#include "%s"' % os.path.join(rel, nm).replace(os.sep, '/')
                      for nm in names)


def robot_dir(name, dirname=None):
    """CodeGen/Cpp/<name>CppCode/ -- one directory per robot, created.

       The directory is named for the robot the USER ASKED ABOUT, and holds
       that robot's <name>.cpp.  A hybrid solve describes two arms, and both
       go in that one file;  the derived arm is distinguished by a suffix on
       its function names (ikin_Panda_a_3_0_a_4_0), never by a directory of
       its own.

       A robot collects more than one artifact here -- FK_numeric<name>.h if
       fkOnly.py has been run, plus whatever the user builds beside it --
       which is why each gets a directory rather than a bare file.

       dirname overrides the whole path, for callers staging into a temporary
       directory.
    """

    if dirname is not None:
        return dirname
    path = os.path.join(DIR_NAME, '%sCppCode' % name)
    if not os.path.isdir(path):
        os.makedirs(path)
    return path


def file_header(what, robot, filename):
    '''The comment banner at the top of a generated .cpp.'''

    hdr = FILE_HEADER.replace('**WHAT**', what)
    hdr = hdr.replace('**ROBOT**', str(robot))
    return hdr.replace('**FILE**', filename)


###############################################################################
#
#    Robot parameters
#

def param_values(M, params=None):
    '''{Symbol: float} for the parameters that HAVE a value, as python bakes them.

       Mech.params, not Robot.params, and for the reason output_python.py
       gives:  Mech.params also carries the ca_i / sa_i symbols that
       forward_kinematics() invents for a twist angle that is not a multiple
       of 90 degrees, and those appear in the equations.

       pvals_numeric() resolves the 'np.cos(al_1)' string fallbacks that
       kin_cl writes for an alpha it cannot evaluate.  If it cannot resolve
       them all, fall back to the raw dict rather than lose the parameters
       that were fine.'''

    try:
        return nik.pvals_numeric(M)
    except Exception:
        out = {}
        for k, v in (M.pvals or {}).items():
            if isinstance(v, str):
                continue
            try:
                out[sp.sympify(k)] = float(v)
            except (TypeError, ValueError):
                pass
        return out


def param_decls(M, params=None, indent=''):
    '''`const double a_2 = 0.432;` for every declared parameter.

       Emitted at namespace scope rather than inside ikin(), mirroring python,
       where the parameters are module-level.  `const`, because the values
       come from the robot definition:  changing one at runtime would mean a
       different robot.'''

    decl = list(params if params is not None
                else (getattr(M, 'params', None) or []))
    pv = param_values(M)

    lines = []
    missing = []
    for p in decl:
        key = sp.sympify(p)
        if key in pv:
            lines.append('%sconst double %s = %s;'
                         % (indent, str(p), expr_cpp(sp.Float(pv[key], 17))))
        else:
            missing.append(str(p))
            lines.append('%sconst double %s = %s;   // USER MUST supply a '
                         'numerical value here' % (indent, str(p), NO_VALUE))
    return '\n'.join(lines), missing


###############################################################################
#
#    Matrices
#

def matrix_cpp(Mx, var, indent='    '):
    '''A sympy Matrix as C++ statements filling `var`, one element per line.

       _matrix_py()'s twin.  One element per statement rather than a braced
       initialiser, because the expressions are long -- Puma's T_06 runs to
       hundreds of characters per element.'''

    lines = []
    for i in range(Mx.rows):
        for j in range(Mx.cols):
            lines.append('%s%s[%d][%d] = %s;'
                         % (indent, var, i, j, expr_cpp(Mx[i, j])))
    return '\n'.join(lines)


def joint_unpack_cpp(syms, indent='    '):
    '''`const double th_1 = q[0];` ... -- the twin of python's tuple unpack.
    '''

    lines = ['%sconst double %s = q[%d];' % (indent, str(s), i)
             for i, s in enumerate(syms)]
    if syms:
        lines.append('%s(void) %s;'
                     % (indent, '; (void) '.join(str(s) for s in syms)))
    return '\n'.join(lines)


def pose_unpack_cpp(indent='    '):
    '''r_11..r_33, Px, Py, Pz out of a Mat4.

       The same twelve names the equations are written in, read row-major
       exactly as python reads them:  T[0,3] is Px in both.'''

    lines = []
    for i in range(3):
        for j in range(3):
            lines.append('%sconst double r_%d%d = T[%d][%d];'
                         % (indent, i + 1, j + 1, i, j))
    for k, nm in enumerate(('Px', 'Py', 'Pz')):
        lines.append('%sconst double %s = T[%d][3];' % (indent, nm, k))

    #  Not every arm's solution mentions all twelve, and an unused `const`
    #  draws a warning.  Declaring them all and casting each to void keeps
    #  this block identical for every robot.
    names = ['r_%d%d' % (i + 1, j + 1) for i in range(3) for j in range(3)]
    names += ['Px', 'Py', 'Pz']
    lines.append('%s(void) %s;' % (indent, '; (void) '.join(names)))
    return '\n'.join(lines)


def name_table_cpp(names, var, indent=''):
    '''`const char* const JOINT_NAMES[] = {"th_1", ...};` plus its length.

       The twin of python's JOINT_NAMES list:  which joint sits at each
       position of a returned row.'''

    if not names:
        #  A zero-length array is ill-formed in C++;  one empty slot is not.
        return ('%sconst char* const %s[] = {""};\n%sconst int N_%s = 0;'
                % (indent, var, indent, var))
    body = ', '.join('"%s"' % n for n in names)
    return ('%sconst char* const %s[] = {%s};\n%sconst int N_%s = %d;'
            % (indent, var, body, indent, var, len(names)))


###############################################################################
#
#    FK (and Jacobian) for one arm
#

def write_fk_module_cpp(M, name, jacobian=True, dirname=None, what=None):
    '''Write FK_numeric<name>.h -- fk_<name>(q), and optionally jacobian_<name>(q).

       The twin of output_numeric_common.write_fk_module(), argument for
       argument.

       FK_numeric, never FK_equations:  output_python.output_FK_python_code()
       owns the name FK_equations<name>, and that is a different artifact -- a
       readable dump of the symbolic T_06 with dummy joint values.  Sharing
       one name would mean whichever ran last quietly replaced the other.

       The header pulls in ikbt_types.h from Cpp_src/ by relative path, as
       every generated file does;  its include guard makes it safe to include
       several of these in one translation unit.

       Written into CodeGen/Cpp/<name>CppCode/ unless dirname says otherwise.
       On the hybrid path that is the TRUE robot's directory even when the FK
       is the derived arm's, since the two arms are one deliverable.

       Returns the path written.'''

    dirname = robot_dir(name, dirname)
    ident = cpp_identifier(name)
    filename = 'FK_numeric%s.h' % name
    path = os.path.join(dirname, filename)
    guard = 'IKBT_FK_NUMERIC_%s_H' % ident.upper()

    #  Build the text first, then open the file.  fk_body_cpp() raises if the
    #  arm's pvals do not resolve every parameter, and open(path, 'w')
    #  truncates before the first write, so generating into a buffer is what
    #  keeps a failure from replacing a good header with half of a new one.
    #
    #  owner=None, so the function names carry the arm's identifier:  a
    #  standalone header sits directly in `namespace ikbt`, with no per-robot
    #  namespace to keep its `fk` from colliding with another robot's.
    body = _StringIO()
    fk_body_cpp(M, name, body, jacobian=jacobian, inline=True)

    with open(path, 'w') as f:
        print(file_header(what or 'Forward kinematics for %s' % name,
                          name, filename), file=f)
        print('#ifndef %s' % guard, file=f)
        print('#define %s' % guard, file=f)
        print('', file=f)
        print(src_includes(['ikbt_types.h'], dirname), file=f)
        print('', file=f)
        print('namespace ikbt {', file=f)
        print('', file=f)
        f.write(body.getvalue())
        print('}   // namespace ikbt', file=f)
        print('', file=f)
        print('#endif   // %s' % guard, file=f)

    return path


def fk_suffix(name, owner):
    """'' for the arm that owns the namespace, '_<ident>' for any other.

       Inside `namespace ikbt::Panda` the true arm's forward kinematics is
       just `fk()`:  the namespace already says which robot it is.  A derived
       arm sharing that namespace keeps its suffix, so that `fk()` and
       `fk_Panda_a_3_0_a_4_0()` cannot be mistaken for each other."""

    if owner is None or str(name) != str(owner):
        return '_' + cpp_identifier(name)
    return ''


def fk_body_cpp(M, name, f, jacobian=True, owner=None, inline=True):
    """fk(), jacobian() and their name table, into an already-open stream.

       The part of write_fk_module_cpp() that is the same wherever it lands --
       a standalone FK_numeric<name>.h or a robot's own <Robot>.cpp -- which
       is everything except the banner, the include guard and the namespace.
       Keeping it separate lets one <Robot>.cpp hold the FK of two arms, which
       the hybrid path needs.

       owner   the robot whose namespace this is emitted into;  see
               fk_suffix().  None means the suffixed, standalone spelling.
       inline  mark the two functions `inline`.  A header needs it, and so
               does a robot file, since nothing stops a user including one."""

    ident = cpp_identifier(name)
    sfx = fk_suffix(name, owner)
    ndof = M.ndof
    syms = nik.joint_symbols(M, ndof)
    pv = nik.pvals_numeric(M)

    T = sp.Matrix(M.T_06).subs(pv)
    J = sp.Matrix(M.J66).subs(pv)[:, :ndof] if jacobian else None

    for label, Mx in (('T_06', T), ('J66', J)):
        if Mx is None:
            continue
        extra = sorted(Mx.free_symbols - set(syms), key=str)
        if extra:
            raise ValueError('%s of %s still contains %s -- pvals did not '
                             'resolve every parameter'
                             % (label, name, [str(s) for s in extra]))

    kw = 'inline ' if inline else ''
    what_arm = ('' if not sfx else '   (%s)' % name)

    #  Into a buffer, then out in one piece.  On the hybrid path this body
    #  lands in the middle of a <Robot>.cpp that already holds another arm, so
    #  a half-written section would spoil the whole robot, not one header.
    f, _out = _StringIO(), f

    print('//  Joint order is the DH CHAIN order, which is what a q vector', file=f)
    print('//  must be in.  It is NOT the order the solver happened to', file=f)
    print('//  solve them in, and it excludes sum-of-angle intermediates.', file=f)
    print(name_table_cpp([str(s) for s in syms], 'FK_JOINT_NAMES%s' % sfx),
          file=f)
    print('const int NDOF%s = %d;' % (sfx, ndof), file=f)
    print('', file=f)

    print('//  q -> 4x4 homogeneous transform of frame 6 in the base frame.%s'
          % what_arm, file=f)
    print('%sMat4 fk%s(const JointVec &q)' % (kw, sfx), file=f)
    print('{', file=f)
    print(joint_unpack_cpp(syms), file=f)
    print('    Mat4 T;', file=f)
    print(matrix_cpp(T, 'T'), file=f)
    print('    return T;', file=f)
    print('}', file=f)
    print('', file=f)

    if jacobian:
        print('//  q -> 6 x %d Jacobian, EXPRESSED IN FRAME 6.%s'
              % (ndof, what_arm), file=f)
        print('//', file=f)
        print('//  Frame 6, not the base frame:  that is what IKBT computes', file=f)
        print('//  and stores as J66.  Rotate it with jacobian_base() before', file=f)
        print('//  comparing against a pose error, which lives in the base', file=f)
        print('//  frame.', file=f)
        print('%sMatrix jacobian%s(const JointVec &q)' % (kw, sfx), file=f)
        print('{', file=f)
        print(joint_unpack_cpp(syms), file=f)
        print('    Matrix J(6, std::vector<double>(%d, 0.0));' % ndof, file=f)
        print(matrix_cpp(J, 'J'), file=f)
        print('    return J;', file=f)
        print('}', file=f)
        print('', file=f)

    _out.write(f.getvalue())
    return ident


#####################################################################
#
#   Test code
#
#  The class number must be unique across the whole package.  tests/leavestest
#  imports * from every leaf module, so two test classes of the same name
#  would leave one of them shadowed and silently never run.
#
#  Everything here is string-level or one small robot out of the FK cache, so
#  the suite stays fast and needs no network.  The checks that need a full
#  solve or a long compile live in scripts/cpp_closed_loop_check.py, which is
#  not part of this suite.

import os as _os
import shutil as _shutil
import subprocess as _subprocess
import tempfile as _tempfile
import unittest


class TestSolver031(unittest.TestCase):
    '''The C++ generator's bottom layer:  identifiers, the expression
       printer, parameter declarations, the Cpp_src/ includes, and one real
       FK header generated and compiled.'''

    def runTest(self):
        self.test_cpp_common()

    def _have_gpp(self):
        return _shutil.which('g++') is not None

    def _compiles(self, source, extra=()):
        '''Does this C++ compile with -Wall -Wextra and no warnings?'''

        tmp = _tempfile.mkdtemp(prefix='ikbt_t031_')
        try:
            p = _os.path.join(tmp, 'probe.cpp')
            with open(p, 'w') as f:
                f.write(source)
            cc = _subprocess.run(['g++', '-std=c++11', '-Wall', '-Wextra',
                                  '-fsyntax-only'] + list(extra) + [p],
                                 capture_output=True, text=True)
            return cc.returncode == 0, cc.stderr
        finally:
            _shutil.rmtree(tmp, ignore_errors=True)

    def test_cpp_common(self):
        print('\n\n==========  Test C++ code generator (common layer)  ============')

        #  1.  Identifiers.  'C-Arm' is a legal robot name and 'ikin_C-Arm' is
        #      a subtraction.
        self.assertEqual(cpp_identifier('C-Arm'), 'C_Arm')
        self.assertEqual(cpp_identifier('Puma'), 'Puma')
        self.assertTrue(cpp_identifier('3Dof')[0] == '_')

        #  2.  The expression printer.  Each of these is a case where
        #      python's spelling is not valid C++.
        Px, a_1, th_1, x = sp.symbols('Px a_1 th_1 x')

        src = expr_cpp((Px - a_1) ** 2)
        self.assertNotIn('**', src)
        self.assertIn('std::pow', src)

        src = expr_cpp(sp.sin(th_1) ** 2)
        self.assertNotIn('**', src)

        #  pi at full precision, as a <cmath> constant.
        src = expr_cpp(sp.pi + x)
        self.assertIn('M_PI', src)
        self.assertNotIn('3.1415926 ', src)

        #  A Rational must not become integer division.
        src = expr_cpp(x / 3)
        self.assertIn('1.0/3.0', src)

        #  Abs -> std::fabs.
        self.assertIn('fabs', expr_cpp(sp.Abs(x)))

        #  ... and something outside the allowed list is REFUSED rather
        #  than emitted as something that will not compile.
        with self.assertRaises(ValueError):
            expr_cpp(sp.gamma(x))

        #  3.  Parameters:  a value is baked in, a missing one stops the
        #      compile on purpose.
        class _FakeMech(object):
            params = list(sp.symbols('a_2 d_4'))
            pvals = {sp.Symbol('a_2'): 0.432}

        text, missing = param_decls(_FakeMech())
        self.assertIn('const double a_2 = 0.432', text)
        self.assertIn('const double d_4 = XXXXX', text)
        self.assertEqual(missing, ['d_4'])

        #  4.  The Cpp_src/ includes are relative to the including file, so
        #      they work from a robot directory and from a staging directory
        #      alike, and neither needs -I.
        lines = src_includes(['ikbt_types.h', 'ikbt_dls.h'],
                             _os.path.join(DIR_NAME, 'PumaCppCode'))
        self.assertEqual(lines.split('\n'),
                         ['#include "../../../Cpp_src/ikbt_types.h"',
                          '#include "../../../Cpp_src/ikbt_dls.h"'])
        #  normpath, not exists():  resolve the `..` steps textually.  Going
        #  through the filesystem would require PumaCppCode to exist, which
        #  depends on a solve having been run -- not on the path arithmetic
        #  being right, which is what is under test.
        for ln in lines.split('\n'):
            rel = ln.split('"')[1]
            self.assertTrue(_os.path.isfile(_os.path.normpath(
                _os.path.join(DIR_NAME, 'PumaCppCode', rel))),
                '%s does not resolve to a real header' % rel)

        #  ... and robot_dir() puts the derived arm of a hybrid solve in the
        #      TRUE robot's directory, because the caller names the robot.
        self.assertTrue(robot_dir('Panda', dirname=_os.path.join('x', 'y'))
                        .endswith(_os.path.join('x', 'y')))

        if not self._have_gpp():
            print('  no g++ -- skipping the compile checks')
            return

        #  5.  Every Cpp_src/ header compiles on its own, which is the whole
        #      reason they are files rather than strings in this module.
        for h in ('ikbt_types.h', 'ikbt_linalg.h', 'ikbt_pose_error.h',
                  'ikbt_dls.h', 'ikbt_search.h'):
            ok, err = self._compiles(read_src(h), extra=('-I', SRC_DIR))
            self.assertTrue(ok, '%s does not compile:\n%s' % (h, err[:600]))
            print('  %-22s compiles standalone' % h)

        #  ... and so do all five together in one translation unit, which
        #      is what the include guards are for.
        every = ''.join('#include "%s"\n' % h for h in
                        ('ikbt_types.h', 'ikbt_linalg.h', 'ikbt_pose_error.h',
                         'ikbt_dls.h', 'ikbt_search.h'))
        ok, err = self._compiles(every + 'int main(){return 0;}\n',
                                 extra=('-I', SRC_DIR))
        self.assertTrue(ok, 'the Cpp_src headers do not co-exist:\n%s'
                        % err[:600])
        print('  all five together      compile')

        #  6.  One real FK header, end to end.  Wrist is the fast robot and
        #      comes out of the FK cache in milliseconds.
        import io
        import contextlib

        from ikbtfunctions.ik_driver import load_robot

        tmp = _tempfile.mkdtemp(prefix='ikbt_t031fk_')
        try:
            buf = io.StringIO()
            with contextlib.redirect_stdout(buf):
                M, R, unks = load_robot('Wrist')
                path = write_fk_module_cpp(M, 'Wrist', jacobian=True,
                                           dirname=tmp)
            self.assertTrue(_os.path.exists(path))
            probe = ('#include "FK_numericWrist.h"\n'
                     'int main(){ ikbt::JointVec q(ikbt::NDOF_Wrist, 0.1);\n'
                     '  ikbt::Mat4 T = ikbt::fk_Wrist(q);\n'
                     '  ikbt::Matrix J = ikbt::jacobian_Wrist(q);\n'
                     '  return (T[3][3] == 1.0 && J.size() == 6) ? 0 : 1; }\n')
            ok, err = self._compiles(probe, extra=('-I', tmp))
            self.assertTrue(ok, 'the generated FK header does not compile:\n%s'
                            % err[:600])
            print('  FK_numericWrist.h      generated and compiles')
        finally:
            _shutil.rmtree(tmp, ignore_errors=True)


if __name__ == '__main__':
    print('\n\n===============  Test output_cpp_common ====================')
    suite = unittest.TestLoader().loadTestsFromTestCase(TestSolver031)
    unittest.TextTestRunner(verbosity=2).run(suite)
