#!/usr/bin/python
#
#   output_cpp_common.py --  generated-C++ pieces more than one method needs
#
#   The twin of output_numeric_common.py, and derived from it row by row:  how
#   a sympy expression becomes C++, what a generated translation unit may
#   include, how a robot's parameters are declared, and how the hand-written
#   numerics in Cpp_src/ get into the file.
#
#   THE PYTHON GENERATOR IS THE SPECIFICATION.  Every function here has a named
#   counterpart in output_python.py or output_numeric_common.py and is expected
#   to produce the same numbers;  scripts/cpp_expr_check.py and
#   scripts/cpp_closed_loop_check.py assert that rather than assume it.
#
#   Copyright 2026 University of Washington
#
#   Developed by Blake Hannaford
#   BioRobotics Lab, University of Washington

import os
import re

import sympy as sp

import ikbtbasics.numeric_ik as nik


#  The PARENT of the generated directories.  Each robot gets its own
#  subdirectory under this one -- see robot_dir().
DIR_NAME = os.path.join('CodeGen', 'Cpp')

#  Cpp_src/ IS SOURCE, on the LaTex_src/ precedent:  hand-written C++ that the
#  generator reads and inlines, so a generated .cpp is self-contained.  It is
#  deliberately not under CodeGen/, which cleanCodeGenOutput wipes.
#
#  RESOLVED AGAINST THIS MODULE, not the working directory -- unlike DIR_NAME
#  above, and for the opposite reason.  Output belongs wherever the user ran
#  IKBT from;  this is material shipped with the package and is in one place
#  whatever the caller's cwd happens to be.  A test in tests.leavestest
#  chdir's, and a relative path here made the C++ generator fail inside the
#  suite while working perfectly from the repo root.
SRC_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                       'Cpp_src')

#  Everything a generated module may call.  The SAME SET as
#  output_numeric_common.ALLOWED_FUNCS -- the point of the whitelist is that
#  the two languages accept exactly the same expressions, so that an equation
#  IKBT can emit as python it can also emit as C++.  sympy's C++ printer maps
#  each of these into <cmath>.
ALLOWED_FUNCS = {'sin', 'cos', 'tan', 'asin', 'acos', 'atan', 'atan2',
                 'sqrt', 'Abs', 'exp', 'log'}

#  The banner.  MODULE_HEADER's twin;  **WHAT** and **ROBOT** substitute the
#  same way.
FILE_HEADER = '''//
//  **WHAT**
//
//  Generated by IKBT.  Do not edit:  regenerate with
//      python3 ikSolver.py **ROBOT**
//
//  Build -- no -I, from any working directory.  This file reaches
//  Cpp_src/ and its own siblings by paths relative to ITSELF, so keep
//  this directory intact and where it is relative to Cpp_src/.
//      g++ -std=c++11 -O2 -c **FILE**
//  Run its self-test:
//      g++ -std=c++11 -O2 -DIKBT_MAIN **FILE** -o ik_test -lm && ./ik_test
//
'''

#  What a parameter with no numerical value is emitted as.  A DELIBERATE
#  COMPILE STOP:  g++ says "'XXXXX' was not declared in this scope" and names
#  the line, so a missing link length cannot be silently defaulted to
#  something wrong.  Documented in CodeGen/HOWTO.txt.
#
#  It used to fire for EVERY parameter, including the robots whose pvals are
#  complete -- 25 of 26 generated files could not be compiled, which is why
#  none of them had ever been checked.  Now it fires only where python would
#  also have written XXXXX.
NO_VALUE = 'XXXXX'


def cpp_identifier(name):
    """A robot name turned into a valid C++ identifier.

       py_identifier()'s twin, and the same rules apply for the same reason:
       'C-Arm' is a legal robot name, a legal file name and a legal LaTeX
       label, but 'ikin_C-Arm' is a subtraction."""

    ident = re.sub(r'\W', '_', str(name))
    if ident and ident[0].isdigit():
        ident = '_' + ident          # an identifier may not start with a digit
    return ident


def expr_cpp(e):
    '''C++ source for one sympy expression, or a raised ValueError.

       expr_py()'s twin, and the reason the old generator's defects are gone
       rather than fixed:  sp.cxxcode is a real C++ printer, so

           (Px - a_1)**2   ->  std::pow(Px - a_1, 2)
           sin(x)**2       ->  std::pow(std::sin(x), 2)
           atan2(y,x)+pi/2 ->  std::atan2(y, x) + M_PI_2
           Abs(x)          ->  std::fabs(x)

       all come out right.  What it replaced was a two-line regex over the
       printed python that handled `x**2` and `sin(x)**2` and silently left
       `(Px - a_1)**2` as invalid C++ -- which is what Arm_3 and UR5 shipped.

       It also prints every Rational as `(1.0/3.0)`, so there is no integer
       division hazard, and every Float at 17 significant digits, so a baked
       parameter keeps the value python had.'''

    src = sp.cxxcode(sp.sympify(e), standard='c++11')
    if 'Not supported' in src or '// Not supported' in src:
        raise ValueError('cannot express in C++: %s' % str(e)[:120])
    for f in sp.sympify(e).atoms(sp.Function):
        nm = type(f).__name__
        if nm not in ALLOWED_FUNCS:
            raise ValueError('generated C++ would need %s(), which is not in '
                             'the shared whitelist' % nm)
    return src


def read_src(basename):
    '''One Cpp_src/ header, verbatim.

       For reading a header to CHECK it:  the tests compile each one on its
       own, which is the whole reason Cpp_src/ holds files rather than string
       literals in this module.  Generated files reach these headers by a
       relative #include, which src_includes() emits.'''

    path = os.path.join(SRC_DIR, basename)
    with open(path) as f:
        return f.read()


def src_includes(names, dirname):
    """`#include` lines for the Cpp_src/ headers a generated file needs.

       ONE COPY OF THE SHARED NUMERICS for the whole package, so a fix to
       ikbt_search.h reaches every robot already generated without
       regenerating anything.

       THE PATH IS COMPUTED, NOT SPELLED OUT.  From a robot directory it
       comes out as ../../../Cpp_src/ikbt_types.h, but
       scripts/cpp_closed_loop_check.py stages generated files into a
       temporary directory at no fixed depth, where a hardcoded `../../../`
       would be wrong.  relpath is right from anywhere.

       `#include "..."` resolves against the INCLUDING FILE's directory, so
       nothing here needs -I:
           g++ -std=c++11 -O2 file.cpp -o x -lm

       The headers' own `#include "ikbt_*.h"` lines need no handling:  they
       are siblings inside Cpp_src/ and find each other there.

       Caller supplies the order;  these are five small files and a
       dependency solver for them would be more machinery than the problem.
       The order that works is types, linalg, pose_error, dls, search.
    """

    rel = os.path.relpath(SRC_DIR, os.path.abspath(dirname))
    return '\n'.join('#include "%s"' % os.path.join(rel, nm).replace(os.sep, '/')
                      for nm in names)


def robot_dir(name, dirname=None):
    """CodeGen/Cpp/<name>CppCode/ -- one directory per robot, created.

       ONE SOLVE PER ROBOT, so one directory per robot, named for the robot
       the user ASKED ABOUT.  A hybrid solve emits files under two names --
       IK_hybrid_Panda.cpp and IK_equationsPanda_a_3_0_a_4_0.cpp -- and they
       are one deliverable: the entry point includes the derived arm's closed
       form as a sibling.  So they share PandaCppCode/, and a derived arm
       never gets a directory of its own.  Which arm each file describes is
       in its NAME, which is where that distinction belongs.

       dirname overrides the whole path, for callers staging into a temp
       directory.
    """

    if dirname is not None:
        return dirname
    path = os.path.join(DIR_NAME, '%sCppCode' % name)
    if not os.path.isdir(path):
        os.makedirs(path)
    return path


def file_header(what, robot, filename):
    '''The comment banner at the top of a generated .cpp.'''

    hdr = FILE_HEADER.replace('**WHAT**', what)
    hdr = hdr.replace('**ROBOT**', str(robot))
    return hdr.replace('**FILE**', filename)


###############################################################################
#
#    Robot parameters
#

def param_values(M, params=None):
    '''{Symbol: float} for the parameters that HAVE a value, as python bakes them.

       Mech.params, NOT Robot.params, for the same reason output_python.py
       gives:  Mech.params also carries the ca_i / sa_i that
       forward_kinematics() invented for a twist angle that is not a multiple
       of 90 degrees, and those appear in the equations.  Here an omission is a
       COMPILE error rather than a runtime one, since C++ needs every name
       declared -- which makes it the better of the two failures, but only
       once the values that DO exist are actually emitted.

       pvals_numeric() resolves the 'np.cos(al_1)' string fallbacks that
       kin_cl still writes for an alpha it cannot evaluate.  If it cannot
       resolve the lot, fall back to the raw dict rather than lose the
       parameters that were fine.'''

    try:
        return nik.pvals_numeric(M)
    except Exception:
        out = {}
        for k, v in (M.pvals or {}).items():
            if isinstance(v, str):
                continue
            try:
                out[sp.sympify(k)] = float(v)
            except (TypeError, ValueError):
                pass
        return out


def param_decls(M, params=None, indent=''):
    '''`const double a_2 = 0.432;` for every declared parameter.

       NAMESPACE SCOPE, not inside ikin().  That mirrors python, where the
       parameters are module-level so a caller can inspect or override them;
       the old C++ declared them as locals inside the function, where nothing
       outside could see them.

       `const`, because the python module's values come from the robot
       definition and overriding one at runtime means you have a different
       robot.  A user editing the file to supply an XXXXX edits a const.'''

    decl = list(params if params is not None
                else (getattr(M, 'params', None) or []))
    pv = param_values(M)

    lines = []
    missing = []
    for p in decl:
        key = sp.sympify(p)
        if key in pv:
            lines.append('%sconst double %s = %s;'
                         % (indent, str(p), expr_cpp(sp.Float(pv[key], 17))))
        else:
            missing.append(str(p))
            lines.append('%sconst double %s = %s;   // USER MUST supply a '
                         'numerical value here' % (indent, str(p), NO_VALUE))
    return '\n'.join(lines), missing


###############################################################################
#
#    Matrices
#

def matrix_cpp(Mx, var, indent='    '):
    '''A sympy Matrix as C++ statements filling `var`, one element per line.

       _matrix_py()'s twin.  An element at a time rather than a braced
       initialiser:  the expressions are long (Puma's T_06 runs to hundreds of
       characters), and one element per line is what makes a compiler
       diagnostic point at something.'''

    lines = []
    for i in range(Mx.rows):
        for j in range(Mx.cols):
            lines.append('%s%s[%d][%d] = %s;'
                         % (indent, var, i, j, expr_cpp(Mx[i, j])))
    return '\n'.join(lines)


def joint_unpack_cpp(syms, indent='    '):
    '''`const double th_1 = q[0];` ... -- the twin of python's tuple unpack.

       With a (void) sweep after it.  Not every matrix mentions every joint --
       a wrist's J66 does not depend on its own first angle -- and an unused
       const is a -Wunused-variable warning.  Unpacking all of them keeps the
       block identical for every robot and every matrix, which is worth more
       than the warnings cost to silence.'''

    lines = ['%sconst double %s = q[%d];' % (indent, str(s), i)
             for i, s in enumerate(syms)]
    if syms:
        lines.append('%s(void) %s;'
                     % (indent, '; (void) '.join(str(s) for s in syms)))
    return '\n'.join(lines)


def pose_unpack_cpp(indent='    '):
    '''r_11..r_33, Px, Py, Pz out of a Mat4.

       The same twelve names the equations are written in, and the same
       ROW-MAJOR reading python does:  T[0,3] is Px in both.'''

    lines = []
    for i in range(3):
        for j in range(3):
            lines.append('%sconst double r_%d%d = T[%d][%d];'
                         % (indent, i + 1, j + 1, i, j))
    for k, nm in enumerate(('Px', 'Py', 'Pz')):
        lines.append('%sconst double %s = T[%d][3];' % (indent, nm, k))

    #  Not every arm's solution mentions all twelve -- a wrist uses no
    #  position at all -- and an unused const is a -Wunused-variable warning.
    #  Declaring them unconditionally keeps the block identical for every
    #  robot, which is worth more than the warnings cost to silence.
    names = ['r_%d%d' % (i + 1, j + 1) for i in range(3) for j in range(3)]
    names += ['Px', 'Py', 'Pz']
    lines.append('%s(void) %s;' % (indent, '; (void) '.join(names)))
    return '\n'.join(lines)


def name_table_cpp(names, var, indent=''):
    '''`const char* const JOINT_NAMES[] = {"th_1", ...};` plus its length.

       The twin of python's JOINT_NAMES list.  C has no way to hand back a
       name with a value, so the ORDER is the contract and this table is what
       documents it.'''

    if not names:
        #  A zero-length array is ill-formed in C++;  one empty slot is not.
        return ('%sconst char* const %s[] = {""};\n%sconst int N_%s = 0;'
                % (indent, var, indent, var))
    body = ', '.join('"%s"' % n for n in names)
    return ('%sconst char* const %s[] = {%s};\n%sconst int N_%s = %d;'
            % (indent, var, body, indent, var, len(names)))


###############################################################################
#
#    FK (and Jacobian) for one arm
#

def write_fk_module_cpp(M, name, jacobian=True, dirname=None, what=None):
    '''Write FK_numeric<name>.h -- fk_<name>(q), and optionally jacobian_<name>(q).

       The twin of output_numeric_common.write_fk_module(), argument for
       argument, with the same guard and the same reasoning:

       FK_numeric, NOT FK_equations.  output_python.output_FK_python_code()
       owns FK_equations<name>, which is a readable dump of the symbolic T_06
       with dummy joint values -- a different artifact.  Sharing the name would
       mean whichever ran last silently replaced the other.

       A HEADER, not a .cpp, because something else includes it.  The python
       twin is a module the hybrid and one-variable modules import as a
       sibling;  `#include "FK_numeric<name>.h"` searches the including file's
       own directory first, so the two arrangements are the same arrangement.
       Everything is `inline`, so several translation units may include it.

       It `#include`s ikbt_types.h from Cpp_src/ by relative path, as every
       generated file does.  The include guards make that safe however many
       of them end up in one translation unit.

       Written into CodeGen/Cpp/<name>CppCode/ unless dirname says otherwise.
       On the hybrid path THAT IS THE TRUE ROBOT'S DIRECTORY even when this
       is the derived arm's FK, because the two are one deliverable and the
       entry point includes this file as a sibling.

       THE PARAMETERS ARE BAKED IN, not left as overridable globals -- the
       opposite of IK_equations*, and deliberately: these functions are the
       definition of "the true arm" that Phase II refines against.

       Only the first ndof columns of J66.  It is stored 6x6 for every robot
       and the surplus columns of a short arm are NOT zero -- a padded DH row
       still gets a column computed for it -- so handing them to the solver
       would let it move joints the arm does not have.

       Returns the path written.'''

    dirname = robot_dir(name, dirname)
    ident = cpp_identifier(name)
    ndof = M.ndof
    syms = nik.joint_symbols(M, ndof)
    pv = nik.pvals_numeric(M)

    T = sp.Matrix(M.T_06).subs(pv)
    J = sp.Matrix(M.J66).subs(pv)[:, :ndof] if jacobian else None

    for label, Mx in (('T_06', T), ('J66', J)):
        if Mx is None:
            continue
        extra = sorted(Mx.free_symbols - set(syms), key=str)
        if extra:
            raise ValueError('%s of %s still contains %s -- pvals did not '
                             'resolve every parameter'
                             % (label, name, [str(s) for s in extra]))

    filename = 'FK_numeric%s.h' % name
    path = os.path.join(dirname, filename)
    guard = 'IKBT_FK_NUMERIC_%s_H' % ident.upper()

    with open(path, 'w') as f:
        print(file_header(what or 'Forward kinematics for %s' % name,
                          name, filename), file=f)
        print('#ifndef %s' % guard, file=f)
        print('#define %s' % guard, file=f)
        print('', file=f)
        print(src_includes(['ikbt_types.h'], dirname), file=f)
        print('', file=f)
        print('namespace ikbt {', file=f)
        print('', file=f)

        print('//  Joint order is the DH CHAIN order, which is what a q vector', file=f)
        print('//  must be in.  It is NOT the order the solver happened to', file=f)
        print('//  solve them in, and it excludes sum-of-angle intermediates.', file=f)
        print(name_table_cpp([str(s) for s in syms],
                             'FK_JOINT_NAMES_%s' % ident), file=f)
        print('const int NDOF_%s = %d;' % (ident, ndof), file=f)
        print('', file=f)

        print('//  q -> 4x4 homogeneous transform of frame 6 in the base frame.', file=f)
        print('inline Mat4 fk_%s(const JointVec &q)' % ident, file=f)
        print('{', file=f)
        print(joint_unpack_cpp(syms), file=f)
        print('    Mat4 T;', file=f)
        print(matrix_cpp(T, 'T'), file=f)
        print('    return T;', file=f)
        print('}', file=f)
        print('', file=f)

        if jacobian:
            print('//  q -> 6 x %d Jacobian, EXPRESSED IN FRAME 6.' % ndof, file=f)
            print('//', file=f)
            print('//  Frame 6, not the base frame:  that is what IKBT computes', file=f)
            print('//  and stores as J66.  Rotate it with jacobian_base() before', file=f)
            print('//  comparing against a pose error, which lives in the base', file=f)
            print('//  frame.', file=f)
            print('inline Matrix jacobian_%s(const JointVec &q)' % ident, file=f)
            print('{', file=f)
            print(joint_unpack_cpp(syms), file=f)
            print('    Matrix J(6, std::vector<double>(%d, 0.0));' % ndof, file=f)
            print(matrix_cpp(J, 'J'), file=f)
            print('    return J;', file=f)
            print('}', file=f)
            print('', file=f)

        print('}   // namespace ikbt', file=f)
        print('', file=f)
        print('#endif   // %s' % guard, file=f)

    return path


#####################################################################
#
#   Test code
#
#  TestSolver031, and the number matters:  the generator this replaced
#  carried a `TestSolver010`, which is x2y2_transform's number.  leavestest
#  does `from ikbtleaves.x2y2_transform import *` and then imports nothing
#  from output_cpp, so the C++ generator's one test class was shadowed and
#  had never run -- which is the mechanical reason six defects sat in it for
#  years.
#
#  FAST AND OFFLINE.  Everything here is string-level or one small robot from
#  the FK cache;  the checks that need a solve or a long compile live in
#  scripts/cpp_closed_loop_check.py, which is not part of this suite.

import os as _os
import shutil as _shutil
import subprocess as _subprocess
import tempfile as _tempfile
import unittest


class TestSolver031(unittest.TestCase):
    '''The C++ generator's bottom layer:  identifiers, the expression printer,
       parameter declarations, header inlining, and one real FK header.'''

    def runTest(self):
        self.test_cpp_common()

    def _have_gpp(self):
        return _shutil.which('g++') is not None

    def _compiles(self, source, extra=()):
        '''Does this C++ compile with -Wall -Wextra and no warnings?'''

        tmp = _tempfile.mkdtemp(prefix='ikbt_t031_')
        try:
            p = _os.path.join(tmp, 'probe.cpp')
            with open(p, 'w') as f:
                f.write(source)
            cc = _subprocess.run(['g++', '-std=c++11', '-Wall', '-Wextra',
                                  '-fsyntax-only'] + list(extra) + [p],
                                 capture_output=True, text=True)
            return cc.returncode == 0, cc.stderr
        finally:
            _shutil.rmtree(tmp, ignore_errors=True)

    def test_cpp_common(self):
        print('\n\n==========  Test C++ code generator (common layer)  ============')

        #  1.  Identifiers.  'C-Arm' is a legal robot name and 'ikin_C-Arm' is
        #      a subtraction.
        self.assertEqual(cpp_identifier('C-Arm'), 'C_Arm')
        self.assertEqual(cpp_identifier('Puma'), 'Puma')
        self.assertTrue(cpp_identifier('3Dof')[0] == '_')

        #  2.  THE REGRESSIONS.  Each of these was mis-emitted by the `**`
        #      regex the old generator used instead of a C++ printer.
        Px, a_1, th_1, x = sp.symbols('Px a_1 th_1 x')

        src = expr_cpp((Px - a_1) ** 2)
        self.assertNotIn('**', src)
        self.assertIn('std::pow', src)

        src = expr_cpp(sp.sin(th_1) ** 2)
        self.assertNotIn('**', src)

        #  pi at FULL precision, not the eight digits the old one hardcoded.
        src = expr_cpp(sp.pi + x)
        self.assertIn('M_PI', src)
        self.assertNotIn('3.1415926 ', src)

        #  A Rational must not become integer division.
        src = expr_cpp(x / 3)
        self.assertIn('1.0/3.0', src)

        #  Abs -> std::fabs, which the python whitelist used to refuse.
        self.assertIn('fabs', expr_cpp(sp.Abs(x)))

        #  ... and something outside the shared whitelist is REFUSED rather
        #  than emitted as something that will not compile.
        with self.assertRaises(ValueError):
            expr_cpp(sp.gamma(x))

        #  3.  Parameters:  a value is baked in, a missing one stops the
        #      compile on purpose.
        class _FakeMech(object):
            params = list(sp.symbols('a_2 d_4'))
            pvals = {sp.Symbol('a_2'): 0.432}

        text, missing = param_decls(_FakeMech())
        self.assertIn('const double a_2 = 0.432', text)
        self.assertIn('const double d_4 = XXXXX', text)
        self.assertEqual(missing, ['d_4'])

        #  4.  The Cpp_src/ includes are RELATIVE TO THE INCLUDING FILE, so
        #      they are right from a robot directory and right from a staging
        #      directory, and neither needs -I.
        lines = src_includes(['ikbt_types.h', 'ikbt_dls.h'],
                             _os.path.join(DIR_NAME, 'PumaCppCode'))
        self.assertEqual(lines.split('\n'),
                         ['#include "../../../Cpp_src/ikbt_types.h"',
                          '#include "../../../Cpp_src/ikbt_dls.h"'])
        #  normpath, not exists():  the `..` steps are resolved TEXTUALLY
        #  here.  exists() would walk them through the filesystem and need
        #  PumaCppCode to have been created, which is a fact about a solve
        #  having been run, not about the path arithmetic being right.
        for ln in lines.split('\n'):
            rel = ln.split('"')[1]
            self.assertTrue(_os.path.isfile(_os.path.normpath(
                _os.path.join(DIR_NAME, 'PumaCppCode', rel))),
                '%s does not resolve to a real header' % rel)

        #  ... and robot_dir() puts the derived arm of a hybrid solve in the
        #      TRUE robot's directory, because the caller names the robot.
        self.assertTrue(robot_dir('Panda', dirname=_os.path.join('x', 'y'))
                        .endswith(_os.path.join('x', 'y')))

        if not self._have_gpp():
            print('  no g++ -- skipping the compile checks')
            return

        #  5.  Every Cpp_src/ header compiles ON ITS OWN.  That is the whole
        #      reason they are files rather than strings in this module.
        for h in ('ikbt_types.h', 'ikbt_linalg.h', 'ikbt_pose_error.h',
                  'ikbt_dls.h', 'ikbt_search.h'):
            ok, err = self._compiles(read_src(h), extra=('-I', SRC_DIR))
            self.assertTrue(ok, '%s does not compile:\n%s' % (h, err[:600]))
            print('  %-22s compiles standalone' % h)

        #  ... and so do all five together in one translation unit, which
        #      is what the include guards are for.
        every = ''.join('#include "%s"\n' % h for h in
                        ('ikbt_types.h', 'ikbt_linalg.h', 'ikbt_pose_error.h',
                         'ikbt_dls.h', 'ikbt_search.h'))
        ok, err = self._compiles(every + 'int main(){return 0;}\n',
                                 extra=('-I', SRC_DIR))
        self.assertTrue(ok, 'the Cpp_src headers do not co-exist:\n%s'
                        % err[:600])
        print('  all five together      compile')

        #  6.  ONE REAL FK HEADER, end to end.  Wrist is the fast robot and it
        #      comes out of the FK cache in milliseconds.
        import io
        import contextlib

        from ikbtfunctions.ik_driver import load_robot

        tmp = _tempfile.mkdtemp(prefix='ikbt_t031fk_')
        try:
            buf = io.StringIO()
            with contextlib.redirect_stdout(buf):
                M, R, unks = load_robot('Wrist')
                path = write_fk_module_cpp(M, 'Wrist', jacobian=True,
                                           dirname=tmp)
            self.assertTrue(_os.path.exists(path))
            probe = ('#include "FK_numericWrist.h"\n'
                     'int main(){ ikbt::JointVec q(ikbt::NDOF_Wrist, 0.1);\n'
                     '  ikbt::Mat4 T = ikbt::fk_Wrist(q);\n'
                     '  ikbt::Matrix J = ikbt::jacobian_Wrist(q);\n'
                     '  return (T[3][3] == 1.0 && J.size() == 6) ? 0 : 1; }\n')
            ok, err = self._compiles(probe, extra=('-I', tmp))
            self.assertTrue(ok, 'the generated FK header does not compile:\n%s'
                            % err[:600])
            print('  FK_numericWrist.h      generated and compiles')
        finally:
            _shutil.rmtree(tmp, ignore_errors=True)


if __name__ == '__main__':
    print('\n\n===============  Test output_cpp_common ====================')
    suite = unittest.TestLoader().loadTestsFromTestCase(TestSolver031)
    unittest.TextTestRunner(verbosity=2).run(suite)
