#!/usr/bin/python
#
#   numeric_ik.py --  numerical inverse kinematics by damped least squares
#
#   The numeric half of the hybrid method.  The hybrid solves a SIMPLIFIED arm
#   in closed form and then corrects the answer numerically against the TRUE
#   arm's forward kinematics.  This module is the correction step, and it is
#   deliberately standalone:  it takes an FK callable, a Jacobian callable, a
#   seed and a target pose, and knows nothing about behavior trees, blackboards
#   or the hybrid branch.  That is what lets it be validated on robots which
#   already solve exactly -- perturb a known-good solution, confirm it comes
#   back -- before any of it is wired into the tree.
#
#   WHY DAMPED LEAST SQUARES (Levenberg-Marquardt) rather than plain gradient
#   descent:  dq = J'(JJ' + lam^2 I)^-1 e behaves like Newton away from
#   singularities and degrades GRACEFULLY to gradient descent as lam grows,
#   which is exactly the failure mode a 6R arm hits at a wrist singularity.
#   Plain gradient descent would make that failure permanent.
#
#   ------------------------------------------------------------------------
#   THREE THINGS MEASURED BEFORE WRITING THIS, two of which contradict the plan:
#
#   1. T_06 (4x4) and J66 (6x6) are ALREADY PICKLED for all 32 robots, and
#      their free symbols are exactly the joint variables plus params that
#      appear in pvals.  No new symbolic computation is needed here.
#
#   2. SUM-OF-ANGLE SYMBOLS CANNOT APPEAR in T_06 or J66.  The plan says they do
#      and must be resolved from R.kequation_aux_list first.  Measured, no robot
#      in the set has one -- but the reason is structural, not statistical (BH):
#      EVERY LINK CAN HAVE ONLY ONE JOINT VARIABLE, so a DH-derived link
#      transform has nothing for a th_23 to be.  SOA terms arise WITHIN the FK
#      equations as the sum-of-angles scan rewrites them, and that rewriting
#      lands in the MATRIX EQUATIONS (matrix_equation.Ts) -- not in the product
#      T_06 or in J66, which stay in raw joint variables.
#
#      So this is a property to rely on, not a measurement to re-check when
#      robot 33 arrives.  (BH notes a sum-of-angle simplification *candidate*
#      could in principle show up in a Jacobian term;  finding it would be of
#      minimal benefit, so nothing here looks for one.)
#
#   3. pvals USED NOT TO BE UNIFORMLY NUMERIC, and the pair of robots involved
#      is not the pair the plan names.  Measured over all 32:  Craig417 and
#      Raven-II, not Raven-II and ICP5p5_A21 -- those two are the only ones
#      whose alpha is not a multiple of pi/2, so they are the only ones for
#      which forward_kinematics() invents ca_i/sa_i at all.  It used to write
#      the STRINGS 'np.cos(al_1)' / 'np.sin(pi/4)' into pvals, and those
#      symbols really are in T_06 -- so they had to be RESOLVED, not skipped.
#      dh_analysis.numeric_pvals() DROPS them, which is right for its own
#      zero-tests and wrong here:  a dropped ca1 survives as a free symbol and
#      becomes a spurious lambdify argument.
#
#      forward_kinematics() now evaluates them (2026-09-03), so every pval on
#      every robot is a number.  pvals_numeric() below stays as the guard: the
#      string is still the fallback for an alpha whose symbols have no numeric
#      value, and _lambdify_checked() refuses anything left over.
#   ------------------------------------------------------------------------
#   MEASURED, on Puma, seeded by perturbing a pose generated by its own FK:
#
#       perturbation   converged   mean iterations
#          0.05 rad      10/10           3.0
#          0.20 rad      10/10           4.0
#          0.50 rad      10/10           5.6
#          1.00 rad      10/10          10.2
#          2.00 rad      10/10          19.2
#
#   and the error sequence is quadratic, which is what says the step is a real
#   Gauss-Newton step and not merely a descent direction:
#
#       1.9e-01  1.6e-02  3.4e-04  1.0e-07  2.3e-15
#
#   At the Puma WRIST SINGULARITY (th_5 = 0, joints 4 and 6 colinear) it still
#   converged 10/10 -- which is the damping earning its place;  an undamped
#   Newton step is singular there by construction.
#   ------------------------------------------------------------------------
#
#   Copyright 2026 University of Washington
#
#   Developed by Blake Hannaford
#   BioRobotics Lab, University of Washington

import numpy as np
import sympy as sp

import ikbtbasics.dh_analysis as da


#  Weight on the orientation error, in the model's LENGTH UNITS per radian.
#
#  BH's convergence metric is  ||dp|| + (1 metre) * theta,  which needs to know
#  what a metre is in the model -- and NOTHING IN THE REPO RECORDS A ROBOT'S
#  UNITS.  Measured, they are not even consistent:  Puma is in metres
#  (a_2 = 0.432) while KinovaLite is in millimetres (l_2 = 280, d_5 = 57).  So
#  there is no single correct constant, and guessing one would silently
#  under-weight orientation by 1000x on half the robot set.
#
#  Hence: w_rot is an explicit parameter everywhere, defaulting to "one model
#  length unit per radian".  For BH's 1 m/rad, pass 1.0 on a metre model and
#  1000.0 on a millimetre model.  See w_rot_for() for a unit-free alternative.
W_ROT_DEFAULT = 1.0


###############################################################################
#
#    Turning a pickled Mech into numeric callables
#

def pvals_numeric(M):
    '''Every entry of M.pvals as a float, with the 'np.cos(...)' strings
       RESOLVED rather than dropped.

       Returns {Symbol: float}.  Raises ValueError naming any entry that could
       not be reduced to a number, because a silently-missing param becomes an
       extra lambdify argument and then a confusing arity error a long way from
       here.

       Since 2026-09-03 forward_kinematics() evaluates ca_i/sa_i, so in
       practice there is nothing left to resolve;  the string remains its
       fallback for an alpha whose symbols have no numeric value.  Such a
       string references either another pvals entry ('np.cos(al_1)', Raven-II)
       or a literal ('np.sin(pi/4)', Craig417), so it is resolved AFTER the
       plainly-numeric entries are known.  Two passes, because one string could
       in principle reference another.'''

    raw = dict(M.pvals or {})
    out = {}

    #  Pass 1: the entries that are already numbers.
    leftover = {}
    for k, v in raw.items():
        if isinstance(v, str):
            leftover[k] = v
            continue
        try:
            out[sp.sympify(k)] = float(v)
        except (TypeError, ValueError):
            leftover[k] = v

    #  Pass 2 (and 3): resolve the rest against what is known so far.
    for _ in range(2):
        if not leftover:
            break
        still = {}
        for k, v in leftover.items():
            expr = v
            if isinstance(expr, str):
                #  'np.cos(al_1)' -> 'cos(al_1)';  sympify maps pi to sp.pi.
                expr = expr.replace('np.', '')
            try:
                e = sp.sympify(expr).subs(out)
                out[sp.sympify(k)] = float(e)
            except (TypeError, ValueError, sp.SympifyError):
                still[k] = v
        if len(still) == len(leftover):
            break                      # made no progress; stop looping
        leftover = still

    if leftover:
        raise ValueError('pvals_numeric: could not reduce to numbers: %s'
                         % {str(k): v for k, v in leftover.items()})
    return out


def dof_of(M, maxrows=6):
    '''How many joints this arm really has.

       The DH table is ALWAYS 6 rows -- shorter arms are padded with [0,0,0,0]
       (see CLAUDE.md, "Adding a robot") -- so 6 is the table's height, not the
       arm's DOF.  Counting the leading rows whose joint cell carries a symbol
       gives the real number:  measured, Craig417 and ICP5p5_A21 are 4-DOF
       tables padded to 6.

       This must NOT be taken from the unknown list.  kinematics_pickle()
       extends that list with sum-of-angle variables, so Craig417 reports 5
       unknowns for 4 joints.'''

    n = 0
    for r in range(maxrows):
        (jr, jc), kind = da.joint_cell(M.DH, M.vv, r)
        if not sp.sympify(M.DH[jr, jc]).free_symbols:
            break                      # padding starts here
        n = r + 1
    return n


def joint_symbols(M, ndof=None):
    '''The joint variables in CHAIN ORDER, one per real DH row.

       Read from the DH table via dh_analysis.joint_cell() rather than from
       R.variables, for two reasons:  the unknown list has been EXTENDED with
       sum-of-angle variables (th_23) which are not joint variables, and the DH
       table is what actually fixes the order a q vector must be in.'''

    if ndof is None:
        ndof = dof_of(M)
    syms = []
    for r in range(ndof):
        (jr, jc), kind = da.joint_cell(M.DH, M.vv, r)
        cell = sp.sympify(M.DH[jr, jc])
        #  THE CELL IS NOT ALWAYS THE BARE JOINT VARIABLE.  Wrist's DH table
        #  holds 'B + pi/2' and 'C + pi/2':  the constant is a fixed part of
        #  the mechanism and the JOINT is the symbol inside.  Returning the
        #  whole cell made T_06's free symbols {A,B,C} fail to match
        #  {A, B+pi/2, C+pi/2}, so _lambdify_checked() rejected Wrist outright
        #  -- and the code generators would have named a joint 'B + pi/2'.
        fs = sorted(cell.free_symbols, key=str)
        if len(fs) != 1:
            raise ValueError('joint_symbols: DH row %d joint cell %s does not '
                             'contain exactly one joint variable' % (r, cell))
        syms.append(fs[0])
    return syms


def _lambdify_checked(expr_matrix, syms, what):
    '''lambdify, after proving nothing is left un-substituted.

       A leftover free symbol is the failure this guards:  lambdify would
       happily accept it as a positional argument, and the caller would then be
       passing joint angles into a link-length slot.

       NOTE THE NESTED [syms].  Passing the symbol list wrapped in another list
       tells lambdify to generate a function of ONE sequence argument, which
       unpacks it itself:

           def _lambdifygenerated(_Dummy_34):
               [th_1, th_2, a_2] = _Dummy_34
               return ...

       so the returned callable already takes a q vector and no wrapper is
       needed to spread it.  (The flat form, lambdify(syms, ...), makes one
       parameter per symbol;  it allows per-argument numpy broadcasting, which
       nothing here wants -- every call evaluates a single joint vector.)'''

    extra = sorted((expr_matrix.free_symbols - set(syms)), key=str)
    if extra:
        raise ValueError('numeric_ik: %s still contains %s -- pvals did not '
                         'resolve every parameter' % (what, [str(s) for s in extra]))
    return sp.lambdify([syms], expr_matrix, 'numpy')


def fk_callable(M, ndof=None):
    '''q -> 4x4 homogeneous transform, as pure numpy.  len(q) == dof_of(M).'''
    pv = pvals_numeric(M)
    syms = joint_symbols(M, ndof)
    return _lambdify_checked(sp.Matrix(M.T_06).subs(pv), syms, 'T_06')


def jacobian_callable(M, ndof=None):
    '''q -> 6 x ndof Jacobian EXPRESSED IN FRAME 6 (that is what J66 is).

       ONLY THE FIRST ndof COLUMNS.  J66 is stored 6x6 for every robot, even a
       4-DOF one, and measured, the surplus columns are NOT zero:  a padded DH
       row still gets a Jacobian column computed for it, as though the constant
       0 in its joint cell were a joint.  Handing those to the solver would let
       it "move" joints the arm does not have.

       Use jacobian_base() to rotate the result into the base frame, which is
       where the pose error lives.'''
    if ndof is None:
        ndof = dof_of(M)
    pv = pvals_numeric(M)
    syms = joint_symbols(M, ndof)
    J = sp.Matrix(M.J66).subs(pv)[:, :ndof]
    return _lambdify_checked(J, syms, 'J66')


def jacobian_base(T, J66):
    '''J_0 = blkdiag(R_06, R_06) . J_66.

       J66 is expressed in frame 6;  the residual is expressed in the base
       frame, so the two must be brought into the same frame or every step is
       rotated by an arbitrary amount.'''

    R = np.asarray(T)[:3, :3]
    Z = np.zeros((3, 3))
    Rot = np.vstack([np.hstack([R, Z]), np.hstack([Z, R])])
    return Rot @ np.asarray(J66)


###############################################################################
#
#    The residual and the metric
#

def rotation_angle_axis(Rerr):
    '''(theta, axis) of a rotation matrix, theta in [0, pi].

       Returns axis = [0,0,0] when theta is 0, so theta*axis is a usable
       rotation vector with no special case at the caller.

       The two degenerate cases are handled explicitly rather than left to
       arccos:  near theta = 0 the axis is numerically meaningless (and the
       rotation vector vanishes anyway), and near theta = pi the skew part
       vanishes so the axis has to come from the symmetric part instead.'''

    Rerr = np.asarray(Rerr, dtype=float)
    c = (np.trace(Rerr) - 1.0) / 2.0
    c = min(1.0, max(-1.0, c))                 # arccos domain, always
    theta = float(np.arccos(c))

    if theta < 1e-12:
        return 0.0, np.zeros(3)

    if theta < np.pi - 1e-6:
        axis = np.array([Rerr[2, 1] - Rerr[1, 2],
                         Rerr[0, 2] - Rerr[2, 0],
                         Rerr[1, 0] - Rerr[0, 1]]) / (2.0 * np.sin(theta))
        return theta, axis

    #  theta ~ pi:  the skew part is ~0, so use  R + I = 2 a a'  and take the
    #  best-conditioned column.
    Msym = Rerr + np.eye(3)
    j = int(np.argmax(np.linalg.norm(Msym, axis=0)))
    axis = Msym[:, j]
    n = np.linalg.norm(axis)
    if n < 1e-12:
        return theta, np.zeros(3)
    return theta, axis / n


def pose_error(T, T_d, w_rot=W_ROT_DEFAULT):
    '''(residual, metric) between the current pose T and the target T_d.

       residual is the 6-vector  [dp ; w_rot * theta * axis]  used by the LM
       step.  metric is BH's scalar  ||dp|| + w_rot * theta,  which is what
       convergence is reported and thresholded on.

       The SAME rotation parameterisation and the SAME weight appear in both,
       which is the point:  the step and the stopping test then agree about what
       "closer" means.  The metric is linear in the error rather than
       quadratic-ish, so one threshold means the same thing near and far from
       convergence -- which is why it is this and not a Frobenius norm.'''

    T = np.asarray(T, dtype=float)
    T_d = np.asarray(T_d, dtype=float)

    dp = T_d[:3, 3] - T[:3, 3]
    theta, axis = rotation_angle_axis(T_d[:3, :3] @ T[:3, :3].T)

    residual = np.concatenate([dp, w_rot * theta * axis])
    metric = float(np.linalg.norm(dp) + w_rot * theta)
    return residual, metric


def w_rot_for(M, ndof=6):
    '''A unit-free w_rot:  one characteristic arm length per radian.

       An alternative to picking a physical metre when the model's units are
       unknown -- it says "a radian of orientation error costs about as much as
       being one arm-length away", which is scale-invariant and therefore
       behaves the same on the metre robots and the millimetre ones.  It is NOT
       BH's 1 m/rad;  it is offered for the case where the caller does not know
       the units and wants something defensible.'''

    return float(da.length_scale(M.DH, M.pvals, M.vv, ndof))


###############################################################################
#
#    The solver
#

def solve_numeric(fk, jac, q0, T_d, w_rot=W_ROT_DEFAULT, tol=1e-9,
                  max_iter=100, lam0=1e-3, lam_min=1e-12, lam_max=1e12):
    '''Refine the seed q0 so that fk(q) matches T_d.  Damped least squares.

           fk    q -> 4x4        (from fk_callable)
           jac   q -> 6x6 in frame 6  (from jacobian_callable)

       Returns a dict:  q, metric, iterations, converged, history, reason.

       Never raises on a bad step:  a singular solve or a non-finite FK is
       treated as a REJECTED step, which raises lam and tries again.  That is
       the whole reason for damping, and turning it into an exception would
       make the singularity failure mode fatal rather than graceful.

       The rotation rows of the Jacobian are scaled by w_rot to match the
       residual, whose rotation block is scaled the same way.  Weighting one and
       not the other would solve a different problem than the one being
       measured.'''

    q = np.array(q0, dtype=float).flatten()
    lam = float(lam0)
    I6 = np.eye(6)
    #  6 x ndof.  For ndof < 6 the system is under-determined -- the arm cannot
    #  reach a general 6-DOF pose -- and damped least squares then returns the
    #  best achievable step rather than failing.  That is the correct behaviour,
    #  but it means `converged` can legitimately stay False on such an arm.
    ndof = q.size
    W = np.diag([1.0, 1.0, 1.0, w_rot, w_rot, w_rot])

    def measure(qq):
        T = fk(qq)
        if not np.all(np.isfinite(T)):
            return None, np.inf
        return pose_error(T, T_d, w_rot=w_rot)

    e, m = measure(q)
    history = [m]
    reason = 'max_iter'

    for it in range(max_iter):
        if m <= tol:
            reason = 'converged'
            break

        T = fk(q)
        try:
            J = W @ jacobian_base(T, jac(q))
            A = J @ J.T + (lam ** 2) * I6
            dq = J.T @ np.linalg.solve(A, e)
        except np.linalg.LinAlgError:
            lam = min(lam * 10.0, lam_max)
            if lam >= lam_max:
                reason = 'lam_max'
                break
            continue

        if not np.all(np.isfinite(dq)):
            lam = min(lam * 10.0, lam_max)
            if lam >= lam_max:
                reason = 'lam_max'
                break
            continue

        q_try = q + dq
        e_try, m_try = measure(q_try)

        if m_try < m:
            q, e, m = q_try, e_try, m_try
            lam = max(lam / 3.0, lam_min)
        else:
            lam = min(lam * 3.0, lam_max)
            if lam >= lam_max:
                reason = 'lam_max'
                break

        history.append(m)

    return {'q': q,
            'metric': m,
            'iterations': len(history) - 1,
            'converged': bool(m <= tol),
            'reason': reason if m > tol else 'converged',
            'history': history}


#####################################################################
#
#   Test code
#

import unittest


def _robot(name):
    '''Load a robot with the FK chatter suppressed.'''
    import contextlib
    import io
    from ikbtfunctions.ik_driver import load_robot
    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        return load_robot(name)


class TestSolver022(unittest.TestCase):
    '''Numerical IK:  the callables, the residual, and convergence.

       These tests take ~1.5 s once the FK pickles are warm.  The FIRST run
       after this file is added takes minutes, because it is the first thing in
       the test suite ever to load Craig417 and Raven-II -- the two robots whose
       alpha is not a multiple of pi/2 -- and their forward kinematics has to
       be computed and cached.  That is a one-off, not a regression.'''

    def setUp(self):
        print('\n\n===============  Test numeric_ik  =====================')
        return

    def runTest(self):
        self.test_nikA_pvals_resolves_the_string_entries()
        self.test_nikB_fk_matches_the_independent_oracle()
        self.test_nikC_pose_error_is_zero_at_the_target()
        self.test_nikD_rotation_angle_axis_edge_cases()
        self.test_nikE_converges_from_a_perturbed_exact_solution()
        self.test_nikF_jacobian_predicts_the_pose_change()
        self.test_nikG_convergence_is_quadratic()
        self.test_nikH_survives_the_wrist_singularity()
        self.test_nikI_sub_six_dof_arm()

    #  ---------------------------------------------------------------- pvals

    def test_nikA_pvals_resolves_the_string_entries(self):
        '''Craig417 and Raven-II are the two robots whose pvals carry invented
           ca_i/sa_i entries, and those symbols really do appear in T_06 -- so
           they must be RESOLVED to numbers.  dh_analysis.numeric_pvals() drops
           a non-numeric one, which would leave ca1 as a free symbol and a
           spurious lambdify argument.  (kin_cl has evaluated them since
           2026-09-03;  this asserts the property rather than the mechanism, so
           it still holds if the string fallback is ever taken.)'''

        fs = ' numeric_ik pvals FAIL'
        for name in ('Craig417', 'Raven-II'):
            M, R, unks = _robot(name)
            pv = pvals_numeric(M)
            for k, v in pv.items():
                self.assertTrue(np.isfinite(v),
                                fs + ' (%s: %s is not finite)' % (name, k))
            #  the whole point: T_06 has nothing left over
            left = sp.Matrix(M.T_06).subs(pv).free_symbols - set(joint_symbols(M))
            self.assertEqual(left, set(),
                             fs + ' (%s left %s unresolved)'
                             % (name, sorted(str(s) for s in left)))

        #  and a clean robot is unaffected
        M, R, unks = _robot('Puma')
        self.assertEqual(len(pvals_numeric(M)), len(M.pvals), fs + ' (Puma)')

    #  ------------------------------------------------------------------- FK

    def test_nikB_fk_matches_the_independent_oracle(self):
        '''The lambdified T_06 must agree with dh_analysis's pure-numpy Link_N
           chain.  Two independent paths to the same matrix is cheap insurance:
           a sign error or a transposed link would otherwise show up much later
           as "the numerics do not converge".'''

        fs = ' numeric_ik FK-vs-oracle FAIL'
        rng = np.random.RandomState(0)

        for name in ('Puma', 'KinovaLite', 'Craig417', 'ICP5p5_A21'):
            M, R, unks = _robot(name)
            ndof = dof_of(M)
            fk = fk_callable(M, ndof)
            rows, slots, kinds, defaulted = da.compile_rows(M.DH, M.pvals,
                                                            M.vv, ndof)
            for _ in range(4):
                q = [rng.uniform(-np.pi, np.pi) if k == 'rot'
                     else rng.uniform(-1.0, 1.0) for k in kinds]
                #  oracle: write the joint values into their DH slots
                rr = rows.copy()
                for r, (jr, jc) in enumerate(slots):
                    rr[jr, jc] = q[r]
                T_oracle = np.asarray(da.fk_numeric(rr, ndof), dtype=float)
                T_lam = fk(q)
                err = np.max(np.abs(T_lam - T_oracle))
                self.assertLess(err, 1e-9,
                                fs + ' (%s: max elementwise error %g)'
                                % (name, err))

    #  --------------------------------------------------------------- metric

    def test_nikC_pose_error_is_zero_at_the_target(self):
        fs = ' numeric_ik pose_error FAIL'
        M, R, unks = _robot('Puma')
        fk = fk_callable(M)
        q = [0.3, -0.4, 0.5, 0.6, -0.7, 0.8]
        T = fk(q)
        e, m = pose_error(T, T)
        self.assertLess(np.max(np.abs(e)), 1e-12, fs + ' (residual not zero)')
        self.assertLess(m, 1e-12, fs + ' (metric not zero)')

        #  a pure translation of 0.1 must read as exactly 0.1
        T2 = T.copy()
        T2[0, 3] += 0.1
        e, m = pose_error(T, T2)
        self.assertAlmostEqual(m, 0.1, places=9,
                               msg=fs + ' (translation not measured in length units)')

        #  a pure rotation of 0.2 rad must read as w_rot * 0.2
        c, s = np.cos(0.2), np.sin(0.2)
        Rz = np.array([[c, -s, 0], [s, c, 0], [0, 0, 1.0]])
        T3 = T.copy()
        T3[:3, :3] = Rz @ T[:3, :3]
        e, m = pose_error(T, T3, w_rot=3.0)
        self.assertAlmostEqual(m, 3.0 * 0.2, places=9,
                               msg=fs + ' (w_rot not applied to the angle)')

    def test_nikD_rotation_angle_axis_edge_cases(self):
        '''Identity and the theta = pi case, which is where the skew part
           vanishes and a naive axis extraction divides by zero.'''

        fs = ' numeric_ik angle/axis FAIL'
        th, ax = rotation_angle_axis(np.eye(3))
        self.assertEqual(th, 0.0, fs + ' (identity should be 0)')
        self.assertLess(np.linalg.norm(ax), 1e-15, fs + ' (identity axis)')

        #  exactly pi about x
        Rpi = np.diag([1.0, -1.0, -1.0])
        th, ax = rotation_angle_axis(Rpi)
        self.assertAlmostEqual(th, np.pi, places=6, msg=fs + ' (pi angle)')
        self.assertAlmostEqual(abs(ax[0]), 1.0, places=6,
                               msg=fs + ' (pi axis should be +-x, got %s)' % ax)

        #  round trip a known rotation
        for angle in (0.05, 0.7, 2.5, np.pi - 1e-3):
            c, s = np.cos(angle), np.sin(angle)
            Rz = np.array([[c, -s, 0], [s, c, 0], [0, 0, 1.0]])
            th, ax = rotation_angle_axis(Rz)
            self.assertAlmostEqual(th, angle, places=6,
                                   msg=fs + ' (angle %g)' % angle)
            self.assertAlmostEqual(abs(ax[2]), 1.0, places=6,
                                   msg=fs + ' (axis for %g)' % angle)

    #  ----------------------------------------------------------- the solver

    def test_nikE_converges_from_a_perturbed_exact_solution(self):
        '''The core claim.  Take a pose generated BY the FK, perturb the joints,
           and confirm the solver walks back to that pose.

           Uses a pose the arm can certainly reach, so a failure here is the
           solver's and not the target's.'''

        fs = ' numeric_ik convergence FAIL'
        rng = np.random.RandomState(7)

        for name, w in (('Puma', 1.0), ('KinovaLite', 1000.0)):
            M, R, unks = _robot(name)
            fk = fk_callable(M)
            jac = jacobian_callable(M)

            #  scale the tolerance to the model:  1e-9 m on a metre robot is
            #  1e-6 mm on a millimetre one, which is not the same demand.
            tol = 1e-8 * max(1.0, w)

            q_true = np.array([0.4, -0.6, 0.7, 0.9, -0.5, 0.3])
            T_d = fk(q_true)

            for trial in range(3):
                q0 = q_true + rng.uniform(-0.15, 0.15, 6)
                res = solve_numeric(fk, jac, q0, T_d, w_rot=w, tol=tol,
                                    max_iter=200)
                self.assertTrue(res['converged'],
                                fs + ' (%s trial %d: metric %g after %d iters, %s)'
                                % (name, trial, res['metric'],
                                   res['iterations'], res['reason']))
                #  the metric must be monotone non-increasing -- LM rejects
                #  any step that would make it worse
                h = res['history']
                self.assertTrue(all(h[i + 1] <= h[i] + 1e-12
                                    for i in range(len(h) - 1)),
                                fs + ' (%s: metric went UP)' % name)

    def test_nikF_jacobian_predicts_the_pose_change(self):
        '''J_0 must actually be the derivative of the pose, in the base frame.

           Checked by finite difference, because a Jacobian in the WRONG FRAME
           still looks plausible -- it has the right size and it changes with q
           -- and would show up only as slow or failed convergence.  This is the
           test that catches a missing blkdiag(R,R).'''

        fs = ' numeric_ik Jacobian FAIL'
        M, R, unks = _robot('Puma')
        fk = fk_callable(M)
        jac = jacobian_callable(M)

        q = np.array([0.35, -0.55, 0.65, 0.85, -0.45, 0.25])
        T0 = fk(q)
        J0 = jacobian_base(T0, jac(q))

        h = 1e-7
        for i in range(6):
            dq = np.zeros(6)
            dq[i] = h
            T1 = fk(q + dq)

            #  finite-difference twist, base frame
            dp = (T1[:3, 3] - T0[:3, 3]) / h
            th, ax = rotation_angle_axis(T1[:3, :3] @ T0[:3, :3].T)
            dw = (th / h) * ax

            self.assertLess(np.linalg.norm(dp - J0[:3, i]), 1e-4,
                            fs + ' (column %d translation: fd %s vs J %s)'
                            % (i, dp, J0[:3, i]))
            self.assertLess(np.linalg.norm(dw - J0[3:, i]), 1e-4,
                            fs + ' (column %d rotation: fd %s vs J %s)'
                            % (i, dw, J0[3:, i]))


    def test_nikG_convergence_is_quadratic(self):
        """The error must roughly SQUARE each step near the solution.

           This is what distinguishes a real Gauss-Newton step from any old
           descent direction:  a wrong-but-plausible Jacobian (mis-scaled, or
           in the wrong frame) still converges, just linearly.  Measured
           sequence on Puma:  1.9e-01  1.6e-02  3.4e-04  1.0e-07  2.3e-15."""

        fs = ' numeric_ik quadratic FAIL'
        M, R, unks = _robot('Puma')
        fk, jac = fk_callable(M), jacobian_callable(M)
        q_true = np.array([0.4, -0.6, 0.7, 0.9, -0.5, 0.3])
        T_d = fk(q_true)
        q0 = q_true + np.array([.15, -.12, .1, .13, -.11, .09])

        res = solve_numeric(fk, jac, q0, T_d, w_rot=1.0, tol=1e-13,
                            max_iter=60)
        self.assertTrue(res['converged'], fs + ' (did not converge)')
        h = [x for x in res['history'] if x > 0]
        self.assertGreaterEqual(len(h), 4, fs + ' (too few steps to judge)')

        #  e_{k+1} <= C e_k^2 over the middle of the run.  Loose C, because the
        #  point is the ORDER, not the constant.
        ok = 0
        for i in range(1, len(h) - 1):
            if h[i + 1] <= 100.0 * h[i] ** 2 + 1e-14:
                ok += 1
        self.assertGreaterEqual(ok, 2,
                                fs + ' (no quadratic steps in %s)'
                                % ['%.1e' % x for x in h])

    def test_nikH_survives_the_wrist_singularity(self):
        """th_5 = 0 makes Puma joints 4 and 6 colinear, so J loses rank and an
           undamped Newton step is singular by construction.  Damped least
           squares must still get there -- this is the whole reason the plan
           specified LM rather than plain gradient descent."""

        fs = ' numeric_ik singularity FAIL'
        M, R, unks = _robot('Puma')
        fk, jac = fk_callable(M), jacobian_callable(M)

        q_s = np.array([0.3, -0.5, 0.6, 0.7, 0.0, 0.2])   # th_5 = 0
        T_d = fk(q_s)

        #  confirm the premise: the Jacobian really is rank-deficient there
        J = jacobian_base(fk(q_s), jac(q_s))
        self.assertLess(np.linalg.matrix_rank(J, tol=1e-9), 6,
                        fs + ' (test premise: J should be singular at th_5=0)')

        rng = np.random.RandomState(3)
        for t in range(4):
            q0 = q_s + rng.uniform(-0.1, 0.1, 6)
            res = solve_numeric(fk, jac, q0, T_d, w_rot=1.0, tol=1e-9,
                                max_iter=300)
            self.assertTrue(res['converged'],
                            fs + ' (trial %d: metric %g, %s)'
                            % (t, res['metric'], res['reason']))

    def test_nikI_sub_six_dof_arm(self):
        """A 4-DOF table padded to 6 rows must use 4 joints, not 6.

           ICP5p5_A21 is the case:  dof_of() must say 4, the Jacobian must be
           6x4 (J66 is stored 6x6 with NON-zero surplus columns), and a
           reachable target must still converge."""

        fs = ' numeric_ik sub-6-DOF FAIL'
        M, R, unks = _robot('ICP5p5_A21')
        n = dof_of(M)
        self.assertEqual(n, 4, fs + ' (dof_of said %d)' % n)

        fk, jac = fk_callable(M), jacobian_callable(M)
        q = np.array([0.3, 0.2, 0.4, 0.5])
        self.assertEqual(jac(q).shape, (6, 4),
                         fs + ' (Jacobian should be 6x%d)' % n)

        T_d = fk(q)
        res = solve_numeric(fk, jac, q + 0.1, T_d, w_rot=1.0, tol=1e-9,
                            max_iter=200)
        self.assertTrue(res['converged'],
                        fs + ' (reachable target: metric %g)' % res['metric'])


def run_test():
    print('\n\n===============  Test numeric_ik  =====================')
    unittest.main(module=__name__, exit=False, argv=['numeric_ik'])


if __name__ == '__main__':
    run_test()
