#!/usr/bin/python
#
#   check_solution_sets.py --  does IKBT's closed form actually SOLVE the robot?
#
#   The baseline record says whether every unknown got an expression, not
#   whether those expressions are RIGHT.  This checks the latter, over SEVERAL
#   random poses, and needs no ground truth and no hand-checking:
#
#       1) generate random poses and for each pose (default 10):
#            generate end effector config: T = FK(pose),
#            generate joint solution versions:  vers = IK(T)
#            for each version v:
#               a) T' = FK(v)
#               b) |T-T'| <= epsilon ?
#          * all versions must satisfy b)
#          * no versions may be identical
#
#   T is generated BY the robot's own forward kinematics, so it is reachable by
#   construction and a failure is the solver's, not the target's.  Every valid
#   IK branch must land back on T;  which branch is which does not matter.
#
#       python3 -m scripts.check_solution_sets Puma           # one robot
#       python3 -m scripts.check_solution_sets Puma Stanford  # several
#       python3 -m scripts.check_solution_sets Puma --poses 20
#       python3 -m scripts.check_solution_sets Puma --gate    # exit 1 on a defect
#
#   TWO DEFECTS ARE CHECKED, AND NEITHER NEEDS A STORED EXPECTATION.
#
#   1.  A version that does not reproduce the pose.  The closed loop is its own
#       oracle:  T came from FK, so "FK(this answer) != T" is wrong, full stop.
#
#   2.  TWO VERSIONS THAT ARE THE SAME POSTURE, whether or not that posture
#       reproduces T.  Compared mod 2*pi on revolute joints, because th and
#       th+2*pi place the arm identically.  If the repeated posture is the
#       right one the solution count is inflated;  if it is a wrong one, the
#       solver produced two spurious branches that are not even distinct.
#       This is a real defect with a known producer:  at the tangency case
#       A^2+B^2 == C^2 the two branches of sinANDcos coincide, but nsolutions
#       stays 2 and two identical rows reach the version machinery -- see
#       test_scB_tangency_duplicate_solutions in ikbtleaves/sinANDcos_solver.py.
#
#   EVERY VERSION MUST REPRODUCE THE POSE.  IKBT enumerates combinations of the
#   unknowns' solution branches without filtering spurious ones, and several
#   robots score less than 100% because of it -- Craig417 at 2-of-4, MiniDD at
#   1-of-4, and the rest of KNOWN INCOMPLETE in scripts/expected.py.  Those are
#   TEST FAILURES here, not accepted states:  a branch handed to the user that
#   puts the arm somewhere other than where it was asked for is wrong, and none
#   of these robots ever had a high-confidence solution (BH, 2026-09-17).  Why
#   they fail is open;  that they fail is not.
#
#   A version that evaluates COMPLEX is excused rather than failed:  that
#   posture does not exist at that pose, which is a fact about the arm.
#
#   scripts/numerical_closed_loop_sol_check.py is the other checker.  It keeps
#   scripts/expected.py, runs against the GENERATED code, and is what the
#   robot_baseline sweep calls -- so the recorded partial counts still have a
#   home, and this script does not need them.
#
#   WHAT IT CANNOT SEE:  a solution that is MISSING.  Every count here descends
#   from the same leaves that produced the solution set, so there is nothing to
#   disagree with.  Detecting that needs an oracle outside IKBT.
#
#   Copyright 2026 University of Washington
#
#   Developed by Blake Hannaford
#   BioRobotics Lab, University of Washington

import argparse
import contextlib
import io
import sys

import numpy as np
import sympy as sp

#  An EVALUATED EXPRESSION either reproduces the pose or it does not, so this
#  is float noise and nothing else.
TOL = 1e-7

#  Two joint vectors closer than this are the same posture.  Looser than TOL:
#  it compares joint angles that came out of different algebraic routes, not a
#  pose against itself.
DUP_TOL = 1e-6

#  pvals resolution, joint naming and the FK callable all live in
#  ikbtbasics.numeric_ik.  Do not copy them here:  the copy drifted last time,
#  naming Wrist's joints 'B + pi/2' and then rejecting the robot because
#  T_06's free symbols did not match.


def solve_once(name):
    '''Solve `name` and return everything the pose checks need.

       Returns (ctx, note).  ctx is None when the robot cannot be checked, and
       `note` then says why -- "could not check" and "checked and wrong" are
       different answers and must not share a code path.

       THE SOLVE IS POSE-INDEPENDENT AND HAPPENS EXACTLY ONCE.  FinalEqnMatrix,
       solListMatrix and the FK callable are all built before any q is chosen,
       so re-solving per pose would multiply the only expensive step in the
       script -- minutes on some robots -- by the pose count and get the same
       matrix back every time.'''

    from ikbtfunctions.ik_driver import load_robot, run_solver
    from ikbtfunctions.bt_assembly import build_default_bt
    import ikbtbasics.numeric_ik as nik

    buf = io.StringIO()
    try:
        with contextlib.redirect_stdout(buf):
            M, R, unknowns = load_robot(name)
            bt, nodes = build_default_bt()
            nodes['compDetect'].read_pause = 0
            for nd in ('symLoop', 'symLoop_onevar', 'symLoop_hybrid'):
                if nd in nodes:
                    nodes[nd].progress = False
            R, unks, bb = run_solver(R, unknowns, bt, create_solutions=True)

            #  THIS SCRIPT CHECKS AN UNCONDITIONAL SOLUTION SET OF THIS ARM,
            #  and the two fallback branches do not produce one.  Say so rather
            #  than measuring:  a one-variable solution is exact only where its
            #  assumed value is right, and a hybrid one describes a derived arm,
            #  so poses checked against this robot's FK would fail every version
            #  and report a defect that is not there.  The generated code is
            #  what to check for those -- see the message.
            for key, what in (('onevar_source',
                               'assumes %s is known, so its equations hold only'
                               ' where that value is right'),
                              ('hybrid_source',
                               'describes the derived arm %s, not this one')):
                src = bb.get(key)
                if src:
                    detail = what % (src.get('known') or src.get('derived_robot')
                                     or '?')
                    return None, (NOT_APPLICABLE + 'solved on the %s branch'
                                  ' -- it %s;  check the generated code with '
                                  'scripts/numerical_closed_loop_sol_check.py'
                                  % (key.split('_')[0], detail))

            if not getattr(R, 'solListMatrix', None):
                return None, 'no solution set (robot does not solve)'
            R.make_LHS_versions()
            pv = nik.pvals_numeric(M)
            jsyms = [str(s) for s in nik.joint_symbols(M)]
            ndof = len(jsyms)
            fk = nik.fk_callable(M)
    except Exception as e:
        return None, f'{type(e).__name__}: {str(e)[:70]}'

    #  vv[i] == 1 is a REVOLUTE joint (kin_cl adds qd_i to the angular velocity
    #  for it).  That is the mask for the mod-2*pi comparison below:  wrapping a
    #  prismatic joint's extension by 2*pi would call two different arms' worth
    #  of travel the same posture.
    revolute = [bool(M.vv[i]) for i in range(ndof)]

    ctx = {
        'R': R,
        'fk': fk,
        'pv': pv,
        'jsyms': jsyms,
        'ndof': ndof,
        'revolute': revolute,
        'order': [n.unknown.name for n in R.solution_nodes],
        'nvers': len(R.FinalEqnMatrix),
    }
    return ctx, ''


def joint_poses(n, ndof):
    '''n random joint vectors.

       -pi..pi for revolute joints.  A prismatic joint gets the same numeric
       range, which is arbitrary but harmless:  T = FK(q) is reachable by
       construction for ANY q, so the range affects which part of the workspace
       is probed, never whether the target is legitimate.'''

    return [[np.random.uniform(-np.pi, np.pi) for _ in range(ndof)]
            for _ in range(n)]


def same_posture(qa, qb, revolute):
    '''Are these two joint vectors the same arm configuration?

       Revolute joints are compared MOD 2*pi.  th and th+2*pi place the arm
       identically and both reproduce T, so a plain difference would call one
       posture two solutions -- which is exactly the defect being looked for.'''

    for a, b, rev in zip(qa, qb, revolute):
        d = a - b
        if rev:
            d = (d + np.pi) % (2 * np.pi) - np.pi
        if abs(d) > DUP_TOL:
            return False
    return True


def distinct_postures(qs, revolute):
    '''Group (row, q) pairs by posture.  Returns a list of lists of rows.'''

    groups = []
    for row, q in qs:
        for g in groups:
            if same_posture(q, g[1], revolute):
                g[0].append(row)
                break
        else:
            groups.append([[row], q])
    return [g[0] for g in groups]


def check_pose(ctx, q_seed, verbose=False):
    '''Evaluate every solution version at one pose.

       Returns a dict:  nvers, n_eval, good, postures, dup_good, dup_bad,
       n_complex, n_uneval.

       `fail_rows` is WHICH versions missed, not just how many:  a count that
       is the same at every pose can still hide a different set of versions
       failing each time, which is the signature of a branch that is only valid
       over part of the workspace.

       `n_eval` counts versions that evaluated to a real joint vector, `good`
       how many of those reproduce the pose, and `postures` how many DISTINCT
       arm configurations the evaluated versions represent.  postures < n_eval
       is duplication, split by whether the repeated posture is the right one
       (dup_good) or a wrong one repeated (dup_bad).'''

    R, fk = ctx['R'], ctx['fk']
    jsyms, order, revolute = ctx['jsyms'], ctx['order'], ctx['revolute']

    q_true = np.array(q_seed[:ctx['ndof']], dtype=float)
    T = np.asarray(fk(q_true), dtype=float)

    pose = dict(ctx['pv'])
    for i in range(3):
        for j in range(3):
            pose[sp.Symbol(f'r_{i + 1}{j + 1}')] = T[i, j]
    for k, nm in enumerate(['Px', 'Py', 'Pz']):
        pose[sp.Symbol(nm)] = T[k, 3]

    n_complex = 0
    n_uneval = 0
    evaluated = []                  # (row, q, reproduces_T) for every real version
    nvers = ctx['nvers']

    for row in range(nvers):
        vals = dict(pose)
        broke = None
        for col in range(len(R.FinalEqnMatrix[row])):
            eq = R.FinalEqnMatrix[row][col]
            try:
                v = complex(sp.N(eq.RHS.subs(vals)))
            except Exception as e:
                broke = f'{eq.LHS} unevaluable ({type(e).__name__})'
                n_uneval += 1
                break
            if abs(v.imag) > 1e-9:
                broke = f'{eq.LHS} complex'   # that POSTURE is not attainable here
                n_complex += 1
                break
            vals[sp.Symbol(str(eq.LHS))] = v.real
        if broke:
            if verbose:
                print(f'      row {row:<3d} {broke}')
            continue

        try:
            #  Read each joint's version NAME from solListMatrix.  Do not build
            #  '<joint>v<row+1>':  an unknown solved early has fewer distinct
            #  versions than there are rows and shares them between rows.
            q = [float(vals[sp.Symbol(R.solListMatrix[row][order.index(j)])])
                 for j in jsyms]
        except (KeyError, ValueError) as e:
            n_uneval += 1
            if verbose:
                print(f'      row {row:<3d} missing joint value ({e})')
            continue

        err = float(np.max(np.abs(np.asarray(fk(q), dtype=float) - T)))
        evaluated.append((row, q, err < TOL))
        if err >= TOL and verbose:
            print(f'      row {row:<3d} FK error {err:.2e}')

    #  DEDUPE OVER EVERY VERSION THAT EVALUATED, not just the ones that land on
    #  T.  Two versions that are one posture is a defect whatever that posture
    #  is:  if they reproduce T the solution count is inflated, and if they do
    #  not it is two spurious branches that are not even distinct from each
    #  other.  A group never straddles the two -- identical q gives identical
    #  FK(q) -- so each group's verdict is the verdict of any member.
    reproduces = {row: ok for row, _, ok in evaluated}
    groups = distinct_postures([(row, q) for row, q, _ in evaluated], revolute)

    dup_good = [g for g in groups if len(g) > 1 and reproduces[g[0]]]
    dup_bad = [g for g in groups if len(g) > 1 and not reproduces[g[0]]]

    if verbose:
        for g in dup_good:
            rows = ', '.join(str(r) for r in g)
            print(f'      rows {rows} are IDENTICAL versions')
        for g in dup_bad:
            rows = ', '.join(str(r) for r in g)
            print(f'      rows {rows} are IDENTICAL versions, and WRONG')

    return {'nvers': nvers,
            'good': sum(1 for _, _, ok in evaluated if ok),
            'n_eval': len(evaluated),
            'fail_rows': frozenset(row for row, _, ok in evaluated if not ok),
            'postures': len(groups),
            'dup_good': dup_good,
            'dup_bad': dup_bad,
            'n_complex': n_complex,
            'n_uneval': n_uneval}


def fmt_range(vals):
    '''"8" if every pose agreed, "2..3" if they did not.'''

    lo, hi = min(vals), max(vals)
    return str(lo) if lo == hi else f'{lo}..{hi}'


def check_robot(name, n_poses, verbose=False):
    '''Solve `name` once, then check it at `n_poses` random poses.

       Returns (summary, note).  summary is None when the robot could not be
       checked at all.'''

    ctx, note = solve_once(name)
    if ctx is None:
        return None, note

    poses = joint_poses(n_poses, ctx['ndof'])

    goods, postures, complexes, unevals = [], [], [], []
    dupg_poses, dupb_poses, empty_poses, bad_poses = [], [], [], []
    fail_sets = []                  # which versions missed, one frozenset per pose

    for i, q in enumerate(poses):
        if verbose:
            qs = ', '.join(f'{x:.3f}' for x in q)
            print(f'    pose {i}  q = [{qs}]')
        r = check_pose(ctx, q, verbose=verbose)
        goods.append(r['good'])
        postures.append(r['postures'])
        complexes.append(r['n_complex'])
        unevals.append(r['n_uneval'])

        if r['dup_good']:
            dupg_poses.append(i)
        if r['dup_bad']:
            dupb_poses.append(i)
        if r['n_eval'] == 0:
            empty_poses.append(i)
        #  ANY version that evaluated and missed the pose is a failure.  A
        #  partial score is not a legitimate outcome here -- see the header.
        if r['n_eval'] > r['good']:
            bad_poses.append((i, r['n_eval'] - r['good']))

        #  THE POSES THEMSELVES ARE NOT WORTH PRINTING.  A defect shows at
        #  essentially every random pose, so the list is just the poses tested
        #  with extra steps.  What IS worth knowing is whether correctness
        #  DEPENDS on the pose -- see fail_sets below.  --verbose still prints
        #  each q, which is the way back to a specific failure.
        fail_sets.append(r['fail_rows'])

    return {'nvers': ctx['nvers'],
            'good': goods,
            'postures': postures,
            'n_complex': sum(complexes),
            'n_uneval': sum(unevals),
            'dupg_poses': dupg_poses,
            'dupb_poses': dupb_poses,
            'empty_poses': empty_poses,
            'bad_poses': bad_poses,
            #  THE INTERESTING QUESTION IS WHETHER CORRECTNESS MOVES WITH THE
            #  POSE.  A stable 2-of-4 reads like two permanently broken
            #  branches;  if the failing SET rotates, it is instead that two of
            #  the four combinations are spurious wherever the arm happens to
            #  be, and which two depends on the configuration.  The counts
            #  alone cannot tell those apart.
            'fail_varies': len(set(fail_sets)) > 1,
            'fail_union': sorted(set().union(*fail_sets)) if fail_sets else [],
            'n_poses': n_poses}, ''


#  Prefix on a note that means "this robot has nothing for this script to
#  check", as opposed to "the check could not be run".  Carried as a prefix
#  rather than a second return value so that check_robot()'s (summary, note)
#  contract is unchanged for every existing caller.
NOT_APPLICABLE = 'n/a: '


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('robots', nargs='+', help='one or more robot names')
    ap.add_argument('--poses', type=int, default=10,
                    help='how many random poses to test (default 10)')
    ap.add_argument('--gate', action='store_true',
                    help='exit 1 if any version misses a pose, two versions are '
                         'identical, or a robot could not be checked')
    ap.add_argument('--verbose', action='store_true',
                    help='say why each failing version failed')
    a = ap.parse_args(argv)

    print('')
    print('  Closed loop IK test:')
    print(f'  1) generate random poses and for each pose ({a.poses}):')
    print('     generate end effector config: T=FK(pose),')
    print('     generate joint solution versions:  vers=IK(T)')
    print('     for each version v:')
    print("        a) T' = FK(v)")
    print("        b) |T-T'| <= epsilon ?")
    print('    * all versions must satisfy b)')
    print('    * no versions may be identical')
    print('')
    print(f'  {"robot":<16} {"versions":>8} {"reproduce":>10}  Number of poses')
    print('  ' + '-' * 70)

    failures = []
    for name in a.robots:
        summary, note = check_robot(name, a.poses, verbose=a.verbose)

        if summary is None:
            #  NOT APPLICABLE IS NOT A FAILURE.  A robot answered by the
            #  one-variable or hybrid branch has no unconditional solution set
            #  of its own for this script to check, and that is a fact about the
            #  robot, not a defect -- the named alternative is where its
            #  generated code gets checked.
            if note.startswith(NOT_APPLICABLE):
                print(f'  {name:<16} {"-":>8} {"-":>10} {"-":>9}  '
                      f'{note[len(NOT_APPLICABLE):]}  <-- n/a')
                continue

            #  COULD NOT CHECK IS A GATE FAILURE.  The robot list is explicit
            #  now, so naming one is a claim that it should check out;  exiting
            #  0 after verifying nothing would answer a question never asked.
            print(f'  {name:<16} {"-":>8} {"-":>10} {"-":>9}  {note}'
                  f'  <-- FAIL')
            failures.append(name)
            continue

        good = fmt_range(summary['good'])
        nvers = summary['nvers']

        #  The note column carries only the exceptions.  A clean robot says
        #  nothing here, so anything printed is worth reading.
        bits = []
        if summary['n_complex']:
            bits.append(f'{summary["n_complex"]} complex')
        if summary['n_uneval']:
            bits.append(f'{summary["n_uneval"]} unevaluable')

        why = []
        if summary['bad_poses']:
            worst = max(n for _, n in summary['bad_poses'])
            why.append(f'{worst} version(s) miss the pose')
            if summary['fail_varies']:
                rows = ','.join(str(r) for r in summary['fail_union'])
                why.append(f'WHICH ones varies by pose (rows {rows})')
        if summary['dupg_poses']:
            why.append(f'identical versions at '
                       f'{len(summary["dupg_poses"])} pose(s)')
        if summary['dupb_poses']:
            why.append(f'identical AND wrong versions at '
                       f'{len(summary["dupb_poses"])} pose(s)')
        if summary['empty_poses']:
            why.append(f'nothing evaluable at '
                       f'{len(summary["empty_poses"])} pose(s)')

        flag = ''
        if why:
            flag = '  <-- FAIL: ' + '; '.join(why)
            failures.append(name)

        note = ('  ' + ', '.join(bits)) if bits else ''
        print(f'  {name:<16} {nvers:>8} {good + "/" + str(nvers):>10} '
              f'{summary["n_poses"]:>9}{note}{flag}')


    print('')
    if a.gate:
        if failures:
            print(f'  GATE FAILED: {", ".join(sorted(set(failures)))}')
            print('')
            return 1
        print('  GATE OK: every version reproduces every pose, and no two')
        print('           versions are identical.')
    print('')
    return 0


if __name__ == '__main__':
    sys.exit(main())
