#!/usr/bin/python
#
#   check_solution_sets.py --  does IKBT's closed form actually SOLVE the robot?
#
#   The baseline record says whether every unknown got an expression, not
#   whether those expressions are RIGHT.  This checks the latter, and needs no
#   ground truth and no hand-checking:
#
#       pick a joint vector q  ->  T = FK(q)  ->  solve IK at T  ->  FK(each
#       solution) must reproduce T
#
#   T is generated BY the robot's own forward kinematics, so it is reachable by
#   construction and a failure is the solver's, not the target's.  Every valid
#   IK branch must land back on T;  which branch is which does not matter.
#
#       python3 -m scripts.check_solution_sets                # every robot it can
#       python3 -m scripts.check_solution_sets --robots Puma  # just these
#       python3 -m scripts.check_solution_sets --gate         # exit 1 if a robot
#                                                        #   misses the count
#                                                        #   recorded for it
#
#   NOT EVERY VERSION IS EXPECTED TO PASS.  Some combinations of the unknowns'
#   solution branches are spurious -- an asin/acos branch that satisfies the
#   equation it came from but not the original pose -- and IKBT does not filter
#   them, so a robot legitimately scoring 4-of-8 is possible.  What must not
#   happen is a robot dropping below the count in scripts/expected.py.
#
#   Copyright 2026 University of Washington
#
#   Developed by Blake Hannaford
#   BioRobotics Lab, University of Washington

import argparse
import contextlib
import io
import sys

import numpy as np
import sympy as sp

from scripts.expected import EXPECT, judge_counts

#  ROBOT_LIST is not present on every branch (it was added with the all-robots
#  baseline harness).  Fall back to a fixed list so this script -- which exists
#  to verify a fix that must land on several branches -- runs anywhere.
try:
    from ikbtfunctions.ik_robots import ROBOT_LIST
except ImportError:                       # older branch without the list
    ROBOT_LIST = ['Puma', 'Pumaoffset', 'Stanford', 'Khat6DOF', 'Olson13',
                  'Brad', 'Chair_Helper', 'Craig417', 'MiniDD', 'DZhang',
                  'KR16', 'UR5', 'Wrist', 'Sims11', 'Bartell', 'Arm_3']


#  THE EXPECTATION TABLE LIVES IN scripts/expected.py, shared with the
#  generated-code checker.  Its (good, total) records a robot that is
#  legitimately not 100% exactly as it measures, rather than leaving it out.
TOL = 1e-7


#  pvals resolution, joint naming and the FK callable all live in
#  ikbtbasics.numeric_ik.  Do not copy them here:  the copy drifted last time,
#  naming Wrist's joints 'B + pi/2' and then rejecting the robot because
#  T_06's free symbols did not match.


def check_robot(name, q_seed=None, verbose=False):
    '''Solve `name`, then verify each solution version against FK.

       Returns (n_good, n_versions, note).  Never raises:  a robot that cannot
       be checked comes back with n_versions == 0 and a note saying why, because
       "could not check" and "checked and wrong" are different answers.'''

    from ikbtfunctions.ik_driver import load_robot, run_solver
    from ikbtfunctions.bt_assembly import build_default_bt
    import ikbtbasics.numeric_ik as nik

    buf = io.StringIO()
    try:
        with contextlib.redirect_stdout(buf):
            M, R, unknowns = load_robot(name)
            bt, nodes = build_default_bt()
            nodes['compDetect'].read_pause = 0
            for nd in ('symLoop', 'symLoop_hybrid'):
                if nd in nodes:
                    nodes[nd].progress = False
            R, unks, bb = run_solver(R, unknowns, bt, create_solutions=True)
            if not getattr(R, 'solListMatrix', None):
                return 0, 0, 'no solution set (robot does not solve)'
            R.make_LHS_versions()
            pv = nik.pvals_numeric(M)
            jsyms = [str(s) for s in nik.joint_symbols(M)]
            ndof = len(jsyms)
            fk = nik.fk_callable(M)
    except Exception as e:
        return 0, 0, '%s: %s' % (type(e).__name__, str(e)[:70])

    order = [n.unknown.name for n in R.solution_nodes]

    #  A pose the arm can certainly reach:  one it generated itself.
    if q_seed is None:
        q_seed = [0.4, -0.6, 0.7, 0.9, -0.5, 0.3]
    q_true = np.array(q_seed[:ndof], dtype=float)
    T = np.asarray(fk(q_true), dtype=float)

    pose = dict(pv)
    for i in range(3):
        for j in range(3):
            pose[sp.Symbol('r_%d%d' % (i + 1, j + 1))] = T[i, j]
    for k, nm in enumerate(['Px', 'Py', 'Pz']):
        pose[sp.Symbol(nm)] = T[k, 3]

    good = 0
    nvers = len(R.FinalEqnMatrix)
    for row in range(nvers):
        vals = dict(pose)
        broke = None
        for col in range(len(R.FinalEqnMatrix[row])):
            eq = R.FinalEqnMatrix[row][col]
            try:
                v = complex(sp.N(eq.RHS.subs(vals)))
            except Exception as e:
                broke = '%s unevaluable (%s)' % (eq.LHS, type(e).__name__)
                break
            if abs(v.imag) > 1e-9:
                broke = '%s complex' % eq.LHS     # branch not reachable here
                break
            vals[sp.Symbol(str(eq.LHS))] = v.real
        if broke:
            if verbose:
                print('    row %-3d %s' % (row, broke))
            continue

        try:
            #  Read each joint's version NAME from solListMatrix.  Do not build
            #  '<joint>v<row+1>':  an unknown solved early has fewer distinct
            #  versions than there are rows and shares them between rows.
            q = [float(vals[sp.Symbol(R.solListMatrix[row][order.index(j)])])
                 for j in jsyms]
        except (KeyError, ValueError) as e:
            if verbose:
                print('    row %-3d missing joint value (%s)' % (row, e))
            continue

        err = float(np.max(np.abs(np.asarray(fk(q), dtype=float) - T)))
        if err < TOL:
            good += 1
        elif verbose:
            print('    row %-3d FK error %.2e' % (row, err))

    return good, nvers, ''


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--robots', nargs='+', help='only these robots')
    ap.add_argument('--gate', action='store_true',
                    help='exit 1 if a robot misses its scripts/expected.py entry')
    ap.add_argument('--verbose', action='store_true',
                    help='say why each failing version failed')
    a = ap.parse_args(argv)

    names = a.robots if a.robots else list(ROBOT_LIST)

    print('')
    print('  Does the closed form actually reproduce the pose it solved for?')
    print('  T is built from each robot\'s own FK, so it is reachable by')
    print('  construction.  Not every version is expected to pass -- see the')
    print('  module docstring -- but a robot in scripts/expected.py must')
    print('  meet the count recorded there.')
    print('')
    print('  %-18s %8s  %s' % ('robot', 'versions', 'note'))
    print('  ' + '-' * 68)

    failures = []
    for name in names:
        good, nvers, note = check_robot(name, verbose=a.verbose)
        if nvers == 0:
            print('  %-18s %8s  %s' % (name, '-', note))
            tag = None
        else:
            frac = '%d/%d' % (good, nvers)
            bad = judge_counts(name, good, nvers)
            flag = ''
            if bad:
                flag = '  <-- REGRESSION: ' + '; '.join(bad)
                failures.append(name)
            elif good == 0:
                flag = '  <-- no version reproduces the pose'
            print('  %-18s %8s%s' % (name, frac, flag))

    print('')
    if a.gate:
        if failures:
            print('  GATE FAILED: %s' % ', '.join(failures))
            return 1
        print('  GATE OK: every robot with a recorded expectation met it.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
