#!/usr/bin/python
#
#   solution_check.py --  does IKBT's closed form actually SOLVE the robot?
#
#   The baseline harness records whether every unknown got an expression.  It
#   has never checked whether those expressions are RIGHT.  That gap is how the
#   solution/version defect survived: `scripts/robot_baseline.py` reported Puma
#   as "solved 7/7" while not one of its eight solution versions could even be
#   evaluated -- every one referenced a `th_1s1` that nothing ever assigns.
#
#   The test here needs no ground truth and no hand-checking:
#
#       pick a joint vector q  ->  T = FK(q)  ->  solve IK at T  ->  FK(each
#       solution) must reproduce T
#
#   T is generated BY the robot's own forward kinematics, so it is reachable by
#   construction and a failure is the solver's, not the target's.  Every valid
#   IK branch must land back on T;  which branch is which does not matter.
#
#       python3 -m scripts.solution_check                # every robot it can
#       python3 -m scripts.solution_check --robots Puma  # just these
#       python3 -m scripts.solution_check --gate         # exit 1 if a
#                                                        #   known-good robot
#                                                        #   is not 100%
#
#   NOT EVERY VERSION IS EXPECTED TO PASS.  The version matrix enumerates
#   combinations of each unknown's solution branches, and some combinations are
#   spurious -- an asin/acos branch that satisfies the equation it came from but
#   not the original pose.  IKBT does not filter those, so a robot legitimately
#   scoring 4-of-8 is possible.  What must not happen is a robot dropping from
#   the count it is known to achieve, which is what --gate checks.
#
#   Copyright 2026 University of Washington
#
#   Developed by Blake Hannaford
#   BioRobotics Lab, University of Washington

import argparse
import contextlib
import io
import sys

import numpy as np
import sympy as sp

from ikbtfunctions.ik_robots import ROBOT_LIST


#  Robots measured to reproduce the target pose on EVERY version, 2026-08-24,
#  immediately after the solution/version fix.  These are the gate: a drop here
#  is a regression in the closed form itself, which no other check would catch.
KNOWN_COMPLETE = ['Puma', 'Pumaoffset', 'Stanford', 'Khat6DOF', 'Olson13',
                  'Brad']

#  Reported, never gated:  these need numeric pvals for every parameter, and a
#  robot whose params are purely symbolic (Wrist has B and C with no values)
#  cannot be checked numerically at all.
TOL = 1e-7


def _pvals_numeric(M):
    """M.pvals as floats, with the 'np.cos(...)' strings RESOLVED.

       forward_kinematics() writes those strings for a robot whose alpha is not
       a multiple of pi/2 (Craig417, Raven-II), and the symbols they define
       really do appear in T_06 -- dropping them would leave a free symbol."""

    raw = dict(M.pvals or {})
    out, left = {}, {}
    for k, v in raw.items():
        if isinstance(v, str):
            left[k] = v
        else:
            try:
                out[sp.sympify(k)] = float(v)
            except (TypeError, ValueError):
                left[k] = v
    for _ in range(2):
        if not left:
            break
        still = {}
        for k, v in left.items():
            try:
                e = sp.sympify(str(v).replace('np.', '')).subs(out)
                out[sp.sympify(k)] = float(e)
            except Exception:
                still[k] = v
        if len(still) == len(left):
            break
        left = still
    if left:
        raise ValueError('unresolved pvals: %s' % sorted(str(k) for k in left))
    return out


def _joint_symbols(M, maxrows=6):
    """The joint variable of each DH row, in chain order, and the real DOF.

       The DH table is always 6 rows;  a shorter arm is padded with [0,0,0,0],
       so the padding rows have no symbol and mark the end of the chain.
       vv[r] == 1 means the joint variable is theta (col 3), else d (col 2)."""

    syms = []
    for r in range(maxrows):
        col = 3 if M.vv[r] else 2
        e = sp.sympify(M.DH[r, col])
        if not e.free_symbols:
            break                        # padding
        syms.append(str(e))
    return syms, len(syms)


def _fk_callable(M, pv, jsyms):
    """q -> 4x4, from the pickled T_06.  Refuses if a parameter is unresolved."""

    T = sp.Matrix(M.T_06).subs(pv)
    extra = sorted(T.free_symbols - set(sp.Symbol(j) for j in jsyms), key=str)
    if extra:
        raise ValueError('T_06 still contains %s' % [str(x) for x in extra])
    return sp.lambdify([[sp.Symbol(j) for j in jsyms]], T, 'numpy')


def check_robot(name, q_seed=None, verbose=False):
    '''Solve `name`, then verify each solution version against FK.

       Returns (n_good, n_versions, note).  Never raises:  a robot that cannot
       be checked comes back with n_versions == 0 and a note saying why, because
       "could not check" and "checked and wrong" are different answers.'''

    from ikbtfunctions.ik_driver import load_robot, run_solver
    from ikbtfunctions.bt_assembly import build_default_bt

    buf = io.StringIO()
    try:
        with contextlib.redirect_stdout(buf):
            M, R, unknowns = load_robot(name)
            bt, nodes = build_default_bt()
            nodes['compDetect'].read_pause = 0
            for nd in ('symLoop', 'symLoop_hybrid'):
                if nd in nodes:
                    nodes[nd].progress = False
            R, unks, bb = run_solver(R, unknowns, bt, create_solutions=True)
            if not getattr(R, 'solListMatrix', None):
                return 0, 0, 'no solution set (robot does not solve)'
            R.make_LHS_versions()
            pv = _pvals_numeric(M)
            jsyms, ndof = _joint_symbols(M)
            fk = _fk_callable(M, pv, jsyms)
    except Exception as e:
        return 0, 0, '%s: %s' % (type(e).__name__, str(e)[:70])

    order = [n.unknown.name for n in R.solution_nodes]

    #  A pose the arm can certainly reach:  one it generated itself.
    if q_seed is None:
        q_seed = [0.4, -0.6, 0.7, 0.9, -0.5, 0.3]
    q_true = np.array(q_seed[:ndof], dtype=float)
    T = np.asarray(fk(q_true), dtype=float)

    pose = dict(pv)
    for i in range(3):
        for j in range(3):
            pose[sp.Symbol('r_%d%d' % (i + 1, j + 1))] = T[i, j]
    for k, nm in enumerate(['Px', 'Py', 'Pz']):
        pose[sp.Symbol(nm)] = T[k, 3]

    good = 0
    nvers = len(R.FinalEqnMatrix)
    for row in range(nvers):
        vals = dict(pose)
        broke = None
        for col in range(len(R.FinalEqnMatrix[row])):
            eq = R.FinalEqnMatrix[row][col]
            try:
                v = complex(sp.N(eq.RHS.subs(vals)))
            except Exception as e:
                broke = '%s unevaluable (%s)' % (eq.LHS, type(e).__name__)
                break
            if abs(v.imag) > 1e-9:
                broke = '%s complex' % eq.LHS     # branch not reachable here
                break
            vals[sp.Symbol(str(eq.LHS))] = v.real
        if broke:
            if verbose:
                print('    row %-3d %s' % (row, broke))
            continue

        try:
            #  Read each joint's version NAME from solListMatrix.  Do not build
            #  '<joint>v<row+1>':  an unknown solved early has fewer distinct
            #  versions than there are rows and shares them between rows.
            q = [float(vals[sp.Symbol(R.solListMatrix[row][order.index(j)])])
                 for j in jsyms]
        except (KeyError, ValueError) as e:
            if verbose:
                print('    row %-3d missing joint value (%s)' % (row, e))
            continue

        err = float(np.max(np.abs(np.asarray(fk(q), dtype=float) - T)))
        if err < TOL:
            good += 1
        elif verbose:
            print('    row %-3d FK error %.2e' % (row, err))

    return good, nvers, ''


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--robots', nargs='+', help='only these robots')
    ap.add_argument('--gate', action='store_true',
                    help='exit 1 if a KNOWN_COMPLETE robot is not 100%%')
    ap.add_argument('--verbose', action='store_true',
                    help='say why each failing version failed')
    a = ap.parse_args(argv)

    names = a.robots if a.robots else list(ROBOT_LIST)

    print('')
    print('  Does the closed form actually reproduce the pose it solved for?')
    print('  T is built from each robot\'s own FK, so it is reachable by')
    print('  construction.  Not every version is expected to pass -- see the')
    print('  module docstring -- but a KNOWN_COMPLETE robot must be 100%.')
    print('')
    print('  %-18s %8s  %s' % ('robot', 'versions', 'note'))
    print('  ' + '-' * 68)

    failures = []
    for name in names:
        good, nvers, note = check_robot(name, verbose=a.verbose)
        if nvers == 0:
            print('  %-18s %8s  %s' % (name, '-', note))
            tag = None
        else:
            frac = '%d/%d' % (good, nvers)
            flag = ''
            if name in KNOWN_COMPLETE and good != nvers:
                flag = '  <-- REGRESSION (was 100%)'
                failures.append(name)
            elif good == 0:
                flag = '  <-- no version reproduces the pose'
            print('  %-18s %8s%s' % (name, frac, flag))

    print('')
    if a.gate:
        if failures:
            print('  GATE FAILED: %s' % ', '.join(failures))
            return 1
        print('  GATE OK: every KNOWN_COMPLETE robot reproduces its pose on '
              'all versions.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
